var pages=[
{page:"Asteraceae",com:"sunflower family",sci:"family Asteraceae",x:"f"},
{page:"Fabaceae",com:"legume family",sci:"family Fabaceae",x:"f"},
{page:"Boraginaceae",com:"borage family",sci:"family Boraginaceae",x:"f"},
{page:"Rosaceae",com:"rose family",sci:"family Rosaceae",x:"f"},
{page:"Asparagaceae",com:"asparagus family",sci:"family Asparagaceae",x:"f"},
{page:"Papaveraceae",com:"poppy family",sci:"family Papaveraceae",x:"f"},
{page:"geranium family",sci:"family Geraniaceae",x:"k"},
{page:"lupines",sci:"Lupinus spp.",x:"k"},
{page:"brodiaea-like flowers",sci:"subfamily Brodiaeoideae",x:"k"},
{page:"Orobanchaceae",com:"broomrape family",sci:"family Orobanchaceae",x:"f"},
{page:"Eschscholzia",sci:"Eschscholzia spp.",x:"k"},
{page:"california poppy",sci:"Eschscholzia californica",x:"o"},
{page:"Brassicaceae",com:"mustard family",sci:"family Brassicaceae",x:"f"},
{page:"thistles",x:"k"},
{page:"Onagraceae",com:"evening primrose family",sci:"family Onagraceae",x:"f"},
{page:"Lamiaceae",com:"mint family",sci:"family Lamiaceae",x:"f"},
{page:"vetches vs. vetchlings",x:"k"},
{page:"Primulaceae",com:"primrose family",sci:"family Primulaceae",x:"f"},
{page:"clovers",sci:"Trifolium spp.",x:"k"},
{page:"Iridaceae",com:"iris family",sci:"family Iridaceae",x:"f"},
{page:"Ranunculaceae",com:"buttercup family",sci:"family Ranunculaceae",x:"f"},
{page:"stork's-bills",sci:"Erodium spp.",x:"k"},
{page:"Apiaceae",com:"carrot family",sci:"family Apiaceae",x:"f"},
{page:"monkeyflowers",sci:"family Phrymaceae",x:"k"},
{page:"paintbrushes",sci:"Castilleja spp.",x:"k"},
{page:"Diplacus",sci:"Diplacus spp.",x:"k"},
{page:"vetches",sci:"Vicia spp.",x:"k"},
{page:"clarkia",sci:"Clarkia spp.",x:"k"},
{page:"orange bush monkeyflower",sci:"Diplacus aurantiacus",x:"o"},
{page:"dandelion-like flowers",x:"k"},
{page:"loosestrifes",sci:"Lysimachia spp.",x:"k"},
{page:"Liliaceae",com:"lily family",sci:"family Liliaceae",x:"f"},
{page:"brambles",sci:"Rubus spp.",x:"k"},
{page:"Plantaginaceae",com:"plantain family",sci:"family Plantaginaceae",x:"f"},
{page:"wild hyacinths",sci:"Dichelostemma spp.",x:"k"},
{page:"bindweed family",sci:"family Convolvulaceae",x:"k"},
{page:"yellow daisies",x:"k"},
{page:"Caprifoliaceae",com:"honeysuckle family",sci:"family Caprifoliaceae",x:"f"},
{page:"Solanaceae",com:"nightshade family",sci:"family Solanaceae",x:"f"},
{page:"nightshades",sci:"Solanum spp.",x:"k"},
{page:"blue-eyed grasses",sci:"Sisyrinchium spp.",x:"k"},
{page:"scarlet pimpernel",sci:"Lysimachia arvensis",x:"o"},
{page:"western blue-eyed grass",sci:"Sisyrinchium bellum",x:"o"},
{page:"Montiaceae",com:"pussypaw family",sci:"family Montiaceae",x:"f"},
{page:"hedgenettles",sci:"Stachys spp.",x:"k"},
{page:"mariposa lilies",sci:"Calochortus spp.",x:"k"},
{page:"small yellow peas",x:"k"},
{page:"Polemoniaceae",com:"phlox family",sci:"family Polemoniaceae",x:"f"},
{page:"owl's clover",x:"k"},
{page:"white daisies",x:"k"},
{page:"broadleaf forget-me-not",sci:"Myosotis latifolia",x:"o"},
{page:"false bindweeds",sci:"Calystegia spp.",x:"k"},
{page:"forget-me-nots",sci:"Myosotis spp.",x:"k"},
{page:"geraniums and cranesbills",sci:"Geranium spp.",x:"k"},
{page:"Malvaceae",com:"mallow family",sci:"family Malvaceae",x:"f"},
{page:"mallows and checkermallows",x:"k"},
{page:"Fagaceae",com:"beach family",sci:"family Fagaceae",x:"f"},
{page:"bittercresses",sci:"Cardamine spp.",x:"k"},
{page:"Rhamnaceae",com:"buckthorn family",sci:"family Rhamnaceae",x:"f"},
{page:"common stork's-bill",sci:"Erodium cicutarium",x:"o"},
{page:"Ericaceae",com:"heather family",sci:"family Ericaceae",x:"f"},
{page:"tarweeds and allies",sci:"tribe Madieae",x:"k"},
{page:"triplet lilies",sci:"Triteleia spp.",x:"k"},
{page:"california blackberry",sci:"Rubus ursinus",x:"o"},
{page:"ceanothus",sci:"Ceanothus spp.",x:"k"},
{page:"milkmaids",sci:"Cardamine californica",x:"o"},
{page:"checkerblooms and checkermallows",sci:"Sidalcea spp.",x:"k"},
{page:"mediterranean stork's-bill",sci:"Erodium botrys",x:"o"},
{page:"ithuriel's spear",sci:"Triteleia laxa",x:"o"},
{page:"larkspurs",sci:"Delphinium spp.",x:"k"},
{page:"Melanthiaceae",com:"trillium family",sci:"family Melanthiaceae",x:"f"},
{page:"Violaceae",com:"violet family",sci:"family Violaceae",x:"f"},
{page:"violets",sci:"Viola spp.",x:"k"},
{page:"blue dicks",sci:"Dichelostemma capitatum",x:"o"},
{page:"california hedge nettle",sci:"Stachys bullata",x:"o"},
{page:"dwarf checkermallow",sci:"Sidalcea malviflora",x:"o"},
{page:"hairy vetch",sci:"Vicia villosa",x:"k"},
{page:"irises",sci:"Iris spp.",x:"k"},
{page:"miniature lupine",sci:"Lupinus bicolor",x:"o"},
{page:"Saxifragaceae",com:"saxifrage family",sci:"family Saxifragaceae",x:"f"},
{page:"shooting stars",sci:"Primula spp.",x:"k"},
{page:"Oxalidaceae",com:"woodsorrel family",sci:"family Oxalidaceae",x:"f"},
{page:"woodsorrels",sci:"Oxalis spp.",x:"k"},
{page:"california buckeye",sci:"Aesculus californica",x:"o"},
{page:"Polygonaceae",com:"knotweed family",sci:"family Polygonaceae",x:"f"},
{page:"milk thistle",sci:"Silybum marianum",x:"o"},
{page:"pacific hound's tongue",sci:"Adelinia grande",x:"o"},
{page:"Sapindaceae",com:"soapberry family",sci:"family Sapindaceae",x:"f"},
{page:"sunflowers",x:"k"},
{page:"sweet peas and vetchlings",sci:"Lathyrus spp.",x:"k"},
{page:"winecup clarkia",sci:"Clarkia purpurea",x:"k"},
{page:"bluewitch nightshade",sci:"Solanum umbelliferum",x:"o"},
{page:"indian paintbrushes",x:"k"},
{page:"Calystegia purpurata",com:"pacific false bindweed",x:"k"},
{page:"Caryophyllaceae",com:"pink family",sci:"family Caryophyllaceae",x:"f"},
{page:"tomcat clover",sci:"Trifolium willdenovii",x:"o"},
{page:"toyon",sci:"Heteromeles arbutifolia",x:"o"},
{page:"blue-eyed marys",sci:"Collinsia spp.",x:"k"},
{page:"buttercups",sci:"Ranunculus spp.",x:"k"},
{page:"Anacardiaceae",com:"cashew family",sci:"family Anacardiaceae",x:"f"},
{page:"common vetch",sci:"Vicia sativa",x:"k"},
{page:"honeysuckles",sci:"Lonicera spp.",x:"k"},
{page:"spring beauties",sci:"Claytonia spp.",x:"k"},
{page:"docks",sci:"Rumex spp.",x:"k"},
{page:"Cucurbitaceae",com:"gourd family",sci:"family Cucurbitaceae",x:"f"},
{page:"manroots",sci:"Marah spp.",x:"k"},
{page:"miner's lettuce",sci:"Claytonia perfoliata",x:"o"},
{page:"oaks",sci:"Quercus spp.",x:"k"},
{page:"pink honeysuckle",sci:"Lonicera hispidula",x:"o"},
{page:"purple owl's-clover",sci:"Castilleja exserta",x:"o"},
{page:"roses",sci:"Rosa spp.",x:"k"},
{page:"silver lupine",sci:"Lupinus albifrons",x:"o"},
{page:"standard thistles",sci:"Cirsium spp.",x:"k"},
{page:"Leptosiphon",com:"baby stars, linanthus, and leptosiphons",sci:"Leptosiphon spp.",x:"k"},
{page:"california buttercup",sci:"Ranunculus californicus",x:"o"},
{page:"california yerba santa",sci:"Eriodictyon californicum",x:"o"},
{page:"ferns",x:"k"},
{page:"Rubiaceae",com:"madder family",sci:"family Rubiaceae",x:"k"},
{page:"pacific poison oak",sci:"Toxicodendron diversilobum",x:"o"},
{page:"plantains",sci:"Plantago spp.",x:"k"},
{page:"silverpuffs and blow wives in seed",x:"k"},
{page:"star thistles",sci:"Centaurea spp.",x:"k"},
{page:"woolly sunflowers",sci:"Eriophyllum spp.",x:"k"},
{page:"common yarrow",sci:"Achillea millefolium",x:"o"},
{page:"coyote mint",sci:"Monardella villosa",x:"o"},
{page:"deervetch",sci:"Acmispon spp.",x:"k"},
{page:"henderson's shooting star",sci:"Primula hendersonii",x:"o"},
{page:"Monardella",sci:"Monardella spp.",x:"k"},
{page:"mustards",x:"k"},
{page:"rose clover",sci:"Trifolium hirtum",x:"o"},
{page:"willowherbs",sci:"Epilobium spp.",x:"k"},
{page:"biscuitroots",sci:"Lomatium spp.",x:"k"},
{page:"bull thistle",sci:"Cirsium vulgare",x:"o"},
{page:"cut-leaved crane's-bill",sci:"Geranium dissectum",x:"o"},
{page:"mule's ears",sci:"Wyethia spp.",x:"k"},
{page:"Nemophila",com:"baby blue eyes",sci:"Nemophila spp.",x:"k"},
{page:"brodiaeas",sci:"Brodiaea spp.",x:"k"},
{page:"california manroot",sci:"Marah fabacea",x:"o"},
{page:"Apocynaceae",com:"dogbane family",sci:"family Apocynaceae",x:"f"},
{page:"elders",sci:"Sambucus spp.",x:"k"},
{page:"fiddlenecks",sci:"Amsinckia spp.",x:"k"},
{page:"Linaceae",com:"flax family",sci:"family Linaceae",x:"f"},
{page:"indian warrior",sci:"Pedicularis densiflora",x:"o"},
{page:"pale flax",sci:"Linum bienne",x:"o"},
{page:"red maids",sci:"Calandrinia menziesii",x:"o"},
{page:"ribwort plantain",sci:"Plantago lanceolata",x:"o"},
{page:"trilliums",sci:"Trillium spp.",x:"k"},
{page:"Viburnaceae",com:"viburnum family",sci:"family Viburnaceae",x:"f"},
{page:"bedstraws",sci:"Galium spp.",x:"k"},
{page:"bird's-foot-trefoils",sci:"Lotus spp.",x:"k"},
{page:"blue elder",sci:"Sambucus cerulea",x:"o"},
{page:"common dandelion",sci:"Taraxacum officinale",x:"o"},
{page:"denseflower indian paintbrush",sci:"Castilleja densiflora",x:"o"},
{page:"four-spot",sci:"Clarkia purpurea ssp. quadrivulnera",x:"o"},
{page:"italian thistle",sci:"Carduus pycnocephalus",x:"o"},
{page:"pacific pea",sci:"Lathyrus vestitus",x:"o"},
{page:"plumeless thistles",sci:"Carduus spp.",x:"k"},
{page:"popcorn flowers",sci:"Plagiobothrys spp.",x:"k"},
{page:"purple chinese houses",sci:"Collinsia heterophylla",x:"o"},
{page:"sanicles",sci:"Sanicula spp.",x:"k"},
{page:"spring vetch",sci:"Vicia sativa ssp. sativa",x:"o"},
{page:"woodland stars",sci:"Lithophragma spp.",x:"k"},
{page:"yellow starthistle",sci:"Centaurea solstitialis",x:"o"},
{page:"baby blue eyes",sci:"Nemophila menziesii",x:"o"},
{page:"beaked hawksbeard",sci:"Crepis vesicaria ssp. taraxacifolia",x:"o"},
{page:"bermuda buttercup",sci:"Oxalis pes-caprae",x:"o"},
{page:"bird's-foot trefoil",sci:"Lotus corniculatus",x:"o"},
{page:"butterfly mariposa lily",sci:"Calochortus venustus",x:"o"},
{page:"california bay",sci:"Umbellularia californica",x:"o"},
{page:"catchweed bedstraw",sci:"Galium aparine",x:"o"},
{page:"fremont's deathcamas",sci:"Toxicoscordion fremontii",x:"o"},
{page:"gilias",sci:"Gilia spp.",x:"k"},
{page:"hawksbeard",sci:"Crepis spp.",x:"k"},
{page:"Lauraceae",com:"laurel family",sci:"family Lauraceae",x:"f"},
{page:"manzanitas",sci:"Arctostaphylos spp.",x:"k"},
{page:"ocean spray",sci:"Holodiscus discolor",x:"k"},
{page:"peppergrasses",sci:"Lepidium spp.",x:"k"},
{page:"redwood sorrel",sci:"Oxalis oregana",x:"o"},
{page:"rusty popcornflower",sci:"Plagiobothrys nothofulvus",x:"o"},
{page:"salsifies",sci:"Tragopogon spp.",x:"k"},
{page:"western columbine",sci:"Aquilegia formosa",x:"o"},
{page:"western heart's ease",sci:"Viola ocellata",x:"o"},
{page:"Amaryllidaceae",com:"amaryllis family",sci:"family Amaryllidaceae",x:"f"},
{page:"Baccharis",sci:"Baccharis spp.",x:"k"},
{page:"baldhip rose",sci:"Rosa gymnocarpa",x:"o"},
{page:"Bellardia",sci:"Bellardia spp.",x:"k"},
{page:"bindweeds",sci:"Convolvulus spp.",x:"k"},
{page:"bush poppy",sci:"Dendromecon rigida",x:"o"},
{page:"california fuchsia",sci:"Epilobium canum",x:"o"},
{page:"california golden violet",sci:"Viola pedunculata",x:"o"},
{page:"california sagebrush",sci:"Artemisia californica",x:"o"},
{page:"common daisy",sci:"Bellis perennis",x:"o"},
{page:"coyote brush",sci:"Baccharis pilularis",x:"o"},
{page:"dove's-foot crane's-bill",sci:"Geranium molle",x:"o"},
{page:"false solomon's seals",sci:"Maianthemum spp.",x:"k"},
{page:"fernald's iris",sci:"Iris fernaldii",x:"o"},
{page:"field bindweed",sci:"Convolvulus arvensis",x:"o"},
{page:"gentian family",sci:"family Gentianaceae",x:"k"},
{page:"harvest brodiaea",sci:"Brodiaea elegans",x:"o"},
{page:"madrones",sci:"Arbutus spp.",x:"k"},
{page:"pacific madrone",sci:"Arbutus menziesii",x:"o"},
{page:"poison hemlock",sci:"Conium maculatum",x:"o"},
{page:"Raphanus",sci:"Raphanus spp.",x:"k"},
{page:"ruby chalice clarkia",sci:"Clarkia rubicunda",x:"o"},
{page:"salsify",sci:"Tragopogon porrifolius",x:"o"},
{page:"sand-spurries",sci:"Spergularia spp.",x:"k"},
{page:"shining pepperweed",sci:"Lepidium nitidum",x:"o"},
{page:"thimbleberry",sci:"Rubus parviflorus",x:"o"},
{page:"tidy tips",sci:"Layia platyglossa",x:"o"},
{page:"tidytips",sci:"Layia spp.",x:"k"},
{page:"Verbenaceae",com:"verbana family",sci:"family Verbenaceae",x:"f"},
{page:"western star flower",sci:"Lysimachia latifolia",x:"o"},
{page:"white globe lily",sci:"Calochortus albus",x:"o"},
{page:"wild radish",sci:"Raphanus sativus",x:"o"},
{page:"woodland madia",sci:"Anisocarpus madioides",x:"o"},
{page:"wormwoods and sagebrushes",sci:"Artemisia spp.",x:"k"},
{page:"yellow mariposa lily",sci:"Calochortus luteus",x:"o"},
{page:"arroyo lupine",sci:"Lupinus succulentus",x:"o"},
{page:"blueblossom",sci:"Ceanothus thyrsiflorus",x:"o"},
{page:"bristly oxtongue",sci:"Helminthotheca echioides",x:"o"},
{page:"buckbrush",sci:"Ceanothus cuneatus",x:"o"},
{page:"Zeltnera",com:"centauries",sci:"Zeltnera spp.",x:"k"},
{page:"common fiddleneck",sci:"Amsinckia menziesii",x:"k"},
{page:"false solomon's seal",sci:"Maianthemum racemosum",x:"o"},
{page:"golden yarrow",sci:"Eriophyllum confertiflorum",x:"o"},
{page:"Poaceae",com:"grasses",sci:"family Poaceae",x:"f"},
{page:"greater periwinkle",sci:"Vinca major",x:"o"},
{page:"Matricaria",sci:"Matricaria spp.",x:"k"},
{page:"mediterranean lineseed",sci:"Bellardia trixago",x:"o"},
{page:"onions",sci:"Allium spp.",x:"k"},
{page:"Orchidaceae",com:"orchid family",sci:"family Orchidaceae",x:"f"},
{page:"periwinkles",sci:"Vinca spp.",x:"k"},
{page:"pineapple-weed",sci:"Matricaria discoidea",x:"o"},
{page:"purple sanicle",sci:"Sanicula bipinnatifida",x:"o"},
{page:"rabbit-tobaccos",sci:"Pseudognaphalium spp.",x:"k"},
{page:"variable linanthus",sci:"Leptosiphon parviflorus",x:"o"},
{page:"western vervain",sci:"Verbena lasiostachys",x:"o"},
{page:"woolly indian paintbrush",sci:"Castilleja foliolosa",x:"o"},
{page:"blow wives",sci:"Achyrachaena mollis",x:"o"},
{page:"bristly dogtail grass",sci:"Cynosurus echinatus",x:"o"},
{page:"broad-leaved sweet pea",sci:"Lathyrus latifolius",x:"o"},
{page:"cabbages and mustards",sci:"Brassica spp.",x:"k"},
{page:"california bee plant",sci:"Scrophularia californica",x:"o"},
{page:"california cudweed",sci:"Pseudognaphalium californicum",x:"o"},
{page:"cat's ears",sci:"Hypochaeris spp.",x:"k"},
{page:"coast indian paintbrush",sci:"Castilleja affinis",x:"o"},
{page:"common cowparsnip",sci:"Heracleum maximum",x:"o"},
{page:"common selfheal",sci:"Prunella vulgaris",x:"o"},
{page:"deerweed",sci:"Acmispon glaber",x:"o"},
{page:"Scrophulariaceae",com:"figwort family",sci:"family Scrophulariaceae",x:"f"},
{page:"hillside woodland star",sci:"Lithophragma heterophyllum",x:"o"},
{page:"indian teasel",sci:"Dipsacus sativus",x:"o"},
{page:"Trillium ovatum",com:"pacific trillium",x:"k"},
{page:"padre's shooting star",sci:"Primula clevelandii",x:"o"},
{page:"sea figs and ice plants",sci:"Carpobrotus spp.",x:"k"},
{page:"Dryopteridaceae",com:"shieldfern family",sci:"family Dryopteridaceae",x:"f"},
{page:"shortpod mustard",sci:"Hirschfeldia incana",x:"o"},
{page:"Aizoaceae",com:"stone plant family",sci:"family Aizoaceae",x:"f"},
{page:"tarweeds",sci:"Madia spp.",x:"k"},
{page:"teasels",sci:"Dipsacus spp.",x:"k"},
{page:"wartleaf ceanothus",sci:"Ceanothus papillosus",x:"o"},
{page:"wavy-leafed soap plant",sci:"Chlorogalum pomeridianum",x:"o"},
{page:"woollyfruit desertparsley",sci:"Lomatium dasycarpum",x:"o"},
{page:"blueberries",sci:"Vaccinium spp.",x:"k"},
{page:"broad-leaved helleborine",sci:"Epipactis helleborine",x:"o"},
{page:"california gilia",sci:"Gilia achilleifolia",x:"o"},
{page:"california goldfields",sci:"Lasthenia californica",x:"o"},
{page:"california huckleberry",sci:"Vaccinium ovatum",x:"o"},
{page:"california wild rose",sci:"Rosa californica",x:"o"},
{page:"chick lupine",sci:"Lupinus microcarpus",x:"o"},
{page:"chile trefoil",sci:"Acmispon wrangelianus",x:"o"},
{page:"coast live oak",sci:"Quercus agrifolia",x:"o"},
{page:"common cat's-ear",sci:"Hypochaeris radicata",x:"o"},
{page:"common chickweed",sci:"Stellaria media",x:"o"},
{page:"creamcups",sci:"Platystemon californicus",x:"o"},
{page:"curly dock",sci:"Rumex crispus",x:"o"},
{page:"elegant clarkia",sci:"Clarkia unguiculata",x:"o"},
{page:"Erythranthe",sci:"Erythranthe spp.",x:"k"},
{page:"fiddle dock",sci:"Rumex pulcher",x:"o"},
{page:"foothill desert-parsley",sci:"Lomatium utriculatum",x:"o"},
{page:"fritillaries",sci:"Fritillaria spp.",x:"k"},
{page:"giant wakerobin",sci:"Trillium chloropetalum",x:"o"},
{page:"goldfields",sci:"Lasthenia spp.",x:"k"},
{page:"gumplants",sci:"Grindelia spp.",x:"k"},
{page:"helleborines",sci:"Epipactis spp.",x:"k"},
{page:"himalayan blackberry",sci:"Rubus armeniacus",x:"o"},
{page:"Araliaceae",com:"ivy family",sci:"family Araliaceae",x:"f"},
{page:"johnnytuck",sci:"Triphysaria eriantha",x:"k"},
{page:"medicks",sci:"Medicago spp.",x:"k"},
{page:"melilots and sweetclovers",sci:"Melilotus spp.",x:"k"},
{page:"rancher's fiddleneck",sci:"Amsinckia menziesii var. intermedia",x:"o"},
{page:"red sand spurrey",sci:"Spergularia rubra",x:"o"},
{page:"Cistaceae",com:"rock-rose family",sci:"family Cistaceae",x:"f"},
{page:"smooth mule-ears",sci:"Wyethia glabra",x:"o"},
{page:"sow thistles",sci:"Sonchus spp.",x:"k"},
{page:"sun cup",sci:"Taraxia ovata",x:"o"},
{page:"Notholithocarpus densiflorus",com:"tanoak",x:"k"},
{page:"white hawkweed",sci:"Hieracium albiflorum",x:"o"},
{page:"american black nightshade",sci:"Solanum americanum",x:"o"},
{page:"american yellowrocket",sci:"Barbarea orthoceras",x:"o"},
{page:"bird's-eye speedwell",sci:"Veronica persica",x:"o"},
{page:"bur clover",sci:"Medicago polymorpha",x:"o"},
{page:"california pitcher sage",sci:"Lepechinia calycina",x:"o"},
{page:"california spikenard",sci:"Aralia californica",x:"o"},
{page:"catchflies",sci:"Silene spp.",x:"k"},
{page:"chamise",sci:"Adenostoma fasciculatum",x:"o"},
{page:"chamomiles",sci:"Anthemis spp.",x:"k"},
{page:"checker lily",sci:"Fritillaria affinis",x:"o"},
{page:"Clematis",sci:"Clematis spp.",x:"k"},
{page:"common hedge parsley",sci:"Torilis arvensis",x:"o"},
{page:"eucalyptus",sci:"Eucalyptus spp.",x:"k"},
{page:"false babystars",sci:"Leptosiphon androsaceus",x:"o"},
{page:"field madder",sci:"Sherardia arvensis",x:"o"},
{page:"field mustard",sci:"Brassica rapa",x:"o"},
{page:"fiesta flower",sci:"Pholistoma auritum",x:"o"},
{page:"greenspot nightshade",sci:"Solanum douglasii",x:"o"},
{page:"hayfield tarweed",sci:"Hemizonia congesta",x:"o"},
{page:"Calystegia subacaulis",com:"hillside false bindweed",x:"k"},
{page:"hillside false bindweed",sci:"Calystegia subacaulis ssp. subacaulis",x:"o"},
{page:"hop trefoil",sci:"Trifolium campestre",x:"o"},
{page:"jeweled onion",sci:"Allium serra",x:"o"},
{page:"milkweeds",sci:"Asclepias spp.",x:"k"},
{page:"modesty",sci:"Whipplea modesta",x:"o"},
{page:"musk stork's-bill",sci:"Erodium moschatum",x:"o"},
{page:"Myrtaceae",com:"myrtle family",sci:"family Myrtaceae",x:"f"},
{page:"narrow-leaved clover",sci:"Trifolium angustifolium",x:"o"},
{page:"narrowleaf mule-ears",sci:"Wyethia angustifolia",x:"o"},
{page:"ookow",sci:"Dichelostemma congestum",x:"o"},
{page:"pipestem clematis",sci:"Clematis lasiantha",x:"o"},
{page:"prickly sowthistle",sci:"Sonchus asper",x:"o"},
{page:"purple star-thistle",sci:"Centaurea calcitrapa",x:"o"},
{page:"red larkspur",sci:"Delphinium nudicaule",x:"o"},
{page:"rough hedgenettle",sci:"Stachys rigida",x:"o"},
{page:"sages",sci:"Salvia spp.",x:"k"},
{page:"san francisco woodland-star",sci:"Lithophragma affine",x:"o"},
{page:"scorpionweeds",sci:"Phacelia spp.",x:"k"},
{page:"seablushes",sci:"Plectritis spp.",x:"k"},
{page:"seep monkeyflower",sci:"Erythranthe guttata",x:"o"},
{page:"shield ferns",sci:"Polystichum spp.",x:"k"},
{page:"Microseris",com:"silverpuffs",sci:"Microseris spp.",x:"k"},
{page:"Uropappus lindleyi",com:"silverpuffs",x:"o"},
{page:"small melilot",sci:"Melilotus indicus",x:"o"},
{page:"speedwells",sci:"Veronica spp.",x:"k"},
{page:"stinking chamomile",sci:"Anthemis cotula",x:"o"},
{page:"western sword fern",sci:"Polystichum munitum",x:"o"},
{page:"american vetch",sci:"Vicia americana",x:"o"},
{page:"andrews' clintonia",sci:"Clintonia andrewsiana",x:"o"},
{page:"bird's-eye gilia",sci:"Gilia tricolor",x:"o"},
{page:"black nightshade",sci:"Solanum nigrum",x:"o"},
{page:"Typhaceae",com:"bulrush family",sci:"family Typhaceae",x:"f"},
{page:"california black oak",sci:"Quercus kelloggii",x:"o"},
{page:"california goldenrod",sci:"Solidago velutina ssp. californica",x:"o"},
{page:"california milkwort",sci:"Rhinotropis californica",x:"o"},
{page:"california plantain",sci:"Plantago erecta",x:"o"},
{page:"california scrub oak",sci:"Quercus berberidifolia",x:"o"},
{page:"cattails",sci:"Typha spp.",x:"k"},
{page:"chicory",sci:"Cichorium intybus",x:"o"},
{page:"chilean sea fig",sci:"Carpobrotus chilensis",x:"o"},
{page:"coast tarweed",sci:"Madia sativa",x:"o"},
{page:"coastal manroot",sci:"Marah oregana",x:"o"},
{page:"common woolly sunflower",sci:"Eriophyllum lanatum",x:"o"},
{page:"cotoneaster",sci:"Cotoneaster spp.",x:"k"},
{page:"cowbag clover",sci:"Trifolium depauperatum",x:"o"},
{page:"douglas iris",sci:"Iris douglasiana",x:"o"},
{page:"douglas' silverpuffs",sci:"Microseris douglasii",x:"o"},
{page:"dwarf brodiaea",sci:"Brodiaea terrestris",x:"o"},
{page:"giant horsetail",sci:"Equisetum telmateia ssp. braunii",x:"o"},
{page:"goldenbushes",sci:"Ericameria spp.",x:"k"},
{page:"goldenrods",sci:"Solidago spp.",x:"k"},
{page:"great horsetail",sci:"Equisetum telmateia",x:"k"},
{page:"hairy gumweed",sci:"Grindelia hirsutula",x:"o"},
{page:"horsetail family",sci:"family Equisetaceae",x:"k"},
{page:"horsetails",sci:"Equisetum spp.",x:"k"},
{page:"lesser hop trefoil",sci:"Trifolium dubium",x:"o"},
{page:"Leucanthemum",sci:"Leucanthemum spp.",x:"k"},
{page:"longhorn seablush",sci:"Plectritis macrocera",x:"o"},
{page:"maidenhair ferns",sci:"Adiantum spp.",x:"k"},
{page:"mallows",sci:"Malva spp.",x:"k"},
{page:"Polygalaceae",com:"milkwort family",sci:"family Polygalaceae",x:"f"},
{page:"muehlenberg's centaury",sci:"Zeltnera muehlenbergii",x:"o"},
{page:"Urticaceae",com:"nettle family",sci:"family Urticaceae",x:"f"},
{page:"nettles",sci:"Urtica spp.",x:"k"},
{page:"plums & cherries",sci:"Prunus spp.",x:"o"},
{page:"red ribbons",sci:"Clarkia concinna",x:"k"},
{page:"rosilla",sci:"Helenium puberulum",x:"o"},
{page:"royal larkspur",sci:"Delphinium variegatum",x:"o"},
{page:"seaside woolly sunflower",sci:"Eriophyllum staechadifolium",x:"o"},
{page:"sheep's sorrel",sci:"Rumex acetosella",x:"o"},
{page:"shrubby rock-roses",sci:"Cistus spp.",x:"k"},
{page:"skunkweed",sci:"Navarretia squarrosa",x:"o"},
{page:"small-flowered catchfly",sci:"Silene gallica",x:"o"},
{page:"sneezeweeds",sci:"Helenium spp.",x:"k"},
{page:"snowberries",sci:"Symphoricarpos spp.",x:"k"},
{page:"stinging nettle",sci:"Urtica dioica",x:"k"},
{page:"sweet fennel",sci:"Foeniculum vulgare",x:"o"},
{page:"wild buckwheats",sci:"Eriogonum spp.",x:"k"},
{page:"yellow bush lupine",sci:"Lupinus arboreus",x:"o"},
{page:"zigzag larkspur",sci:"Delphinium patens",x:"o"},
{page:"alkali heath",sci:"Frankenia salina",x:"o"},
{page:"alkali heliotrope",sci:"Heliotropium curassavicum",x:"o"},
{page:"american asters",sci:"Symphyotrichum spp.",x:"k"},
{page:"beaked hazelnut",sci:"Corylus cornuta",x:"k"},
{page:"bent-flowered fiddleneck",sci:"Amsinckia lunaris",x:"o"},
{page:"big berry manzanita",sci:"Arctostaphylos glauca",x:"o"},
{page:"Betulaceae",com:"birch family",sci:"family Betulaceae",x:"f"},
{page:"black mustard",sci:"Brassica nigra",x:"o"},
{page:"black sage",sci:"Salvia mellifera",x:"o"},
{page:"broad-leaved cattail",sci:"Typha latifolia",x:"o"},
{page:"butter-and-eggs",sci:"Triphysaria eriantha ssp. eriantha",x:"o"},
{page:"Cactaceae",com:"cactus family",sci:"family Cactaceae",x:"f"},
{page:"california hazelnut",sci:"Corylus cornuta ssp. californica",x:"o"},
{page:"california maidenhair fern",sci:"Adiantum jordanii",x:"o"},
{page:"Blechnaceae",com:"chain fern family",sci:"family Blechnaceae",x:"f"},
{page:"chia",sci:"Salvia columbariae",x:"o"},
{page:"Chrysolepis",sci:"Chrysolepis spp.",x:"k"},
{page:"clay mariposa lily",sci:"Calochortus argillosus",x:"o"},
{page:"clustered clover",sci:"Trifolium glomeratum",x:"o"},
{page:"coast silk tassel",sci:"Garrya elliptica",x:"o"},
{page:"coastal larkspur",sci:"Delphinium decorum",x:"o"},
{page:"coastal woodfern",sci:"Dryopteris arguta",x:"o"},
{page:"Cirsium occidentale",com:"cobwebby thistle",x:"k"},
{page:"common madia",sci:"Madia elegans",x:"o"},
{page:"common snowberry",sci:"Symphoricarpos albus",x:"o"},
{page:"coralroots",sci:"Corallorhiza spp.",x:"k"},
{page:"crevice alumroot",sci:"Heuchera micrantha",x:"o"},
{page:"currants and gooseberries",sci:"Ribes spp.",x:"k"},
{page:"davy's centaury",sci:"Zeltnera davyi",x:"o"},
{page:"Cornaceae",com:"dogwood family",sci:"family Cornaceae",x:"f"},
{page:"dogwoods",sci:"Cornus spp.",x:"k"},
{page:"fleabanes and horseweeds",sci:"Erigeron spp.",x:"k"},
{page:"franciscan paintbrush",sci:"Castilleja subinclusa ssp. franciscana",x:"o"},
{page:"fringed checkerbloom",sci:"Sidalcea diploscypha",x:"o"},
{page:"fringed willowherb",sci:"Epilobium ciliatum",x:"o"},
{page:"fringepods",sci:"Thysanocarpus spp.",x:"k"},
{page:"Garryaceae",sci:"family Garryaceae",x:"f"},
{page:"giant chain fern",sci:"Woodwardia fimbriata",x:"o"},
{page:"golden brodiaea",sci:"Triteleia ixioides ssp. ixioides",x:"o"},
{page:"golden chinquapin",sci:"Chrysolepis chrysophylla",x:"k"},
{page:"golden-fleece",sci:"Ericameria arborescens",x:"o"},
{page:"Grossulariaceae",com:"gooseberry family",sci:"family Grossulariaceae",x:"f"},
{page:"gray mule-ears",sci:"Wyethia helenioides",x:"o"},
{page:"hairy ceanothus",sci:"Ceanothus oliganthus",x:"o"},
{page:"heliotrope",sci:"Heliotropium spp.",x:"k"},
{page:"herb robert",sci:"Geranium robertianum",x:"o"},
{page:"hoary rock-rose",sci:"Cistus creticus",x:"o"},
{page:"late cotoneaster",sci:"Cotoneaster coriaceus",x:"o"},
{page:"leafy mistletoes",sci:"Phoradendron spp.",x:"k"},
{page:"lettuces",sci:"Lactuca spp.",x:"k"},
{page:"Micropus",sci:"Micropus spp.",x:"k"},
{page:"mountain phacelia",sci:"Phacelia imbricata",x:"o"},
{page:"narrowleaf milkweed",sci:"Asclepias fascicularis",x:"o"},
{page:"oak mistletoe",sci:"Phoradendron villosum",x:"o"},
{page:"olive",sci:"Olea europaea",x:"o"},
{page:"Oleaceae",com:"olive family",sci:"family Oleaceae",x:"f"},
{page:"oregon bitterroot",sci:"Lewisia rediviva",x:"o"},
{page:"oxeye daisy",sci:"Leucanthemum vulgare",x:"o"},
{page:"pacific aster",sci:"Symphyotrichum chilense",x:"o"},
{page:"pacific sanicle",sci:"Sanicula crassicaulis",x:"o"},
{page:"pacific trillium",sci:"Trillium ovatum ssp. ovatum",x:"o"},
{page:"panicled willowherb",sci:"Epilobium brachycarpum",x:"o"},
{page:"peak rushrose",sci:"Helianthemum scoparium",x:"o"},
{page:"peruvian peppertree",sci:"Schinus molle",x:"o"},
{page:"prettyface",sci:"Triteleia ixioides",x:"k"},
{page:"prickly pears",sci:"Opuntia spp.",x:"k"},
{page:"purple viper's-bugloss",sci:"Echium plantagineum",x:"o"},
{page:"q-tips",com:"Q tips",sci:"Micropus californicus",x:"o"},
{page:"red osier dogwood",sci:"Cornus sericea",x:"k"},
{page:"red vetchling",sci:"Lathyrus cicera",x:"o"},
{page:"sand fringepod",sci:"Thysanocarpus curvipes",x:"o"},
{page:"Santalaceae",com:"sandalwood family",sci:"family Santalaceae",x:"f"},
{page:"santa clara red ribbons",sci:"Clarkia concinna ssp. automixa",x:"o"},
{page:"Frankeniaceae",com:"sea heath family",sci:"family Frankeniaceae",x:"f"},
{page:"sea muilla",sci:"Muilla maritima",x:"o"},
{page:"seaside daisy",sci:"Erigeron glaucus",x:"o"},
{page:"short-flower deervetch",sci:"Acmispon parviflorus",x:"o"},
{page:"silk tassel",sci:"Garrya spp.",x:"k"},
{page:"silver wattle",sci:"Acacia dealbata",x:"o"},
{page:"slender iceplant",sci:"Mesembryanthemum nodiflorum",x:"o"},
{page:"sticky cinquefoil",sci:"Drymocallis glandulosa",x:"o"},
{page:"sticky sand-spurrey",sci:"Spergularia macrotheca",x:"o"},
{page:"stream violet",sci:"Viola glabella",x:"o"},
{page:"tanoak",sci:"Notholithocarpus densiflorus var. densiflorus",x:"o"},
{page:"tasmanian blue gum",sci:"Eucalyptus globulus",x:"o"},
{page:"three-cornered garlic",sci:"Allium triquetrum",x:"o"},
{page:"threeleaf foamflower",sci:"Tiarella trifoliata",x:"o"},
{page:"venus thistle",sci:"Cirsium occidentale var. venustum",x:"o"},
{page:"vinegar weed",sci:"Trichostema lanceolatum",x:"o"},
{page:"viper's-buglosses",sci:"Echium spp.",x:"k"},
{page:"wallflowers",sci:"Erysimum spp.",x:"k"},
{page:"wattles",sci:"Acacia spp.",x:"k"},
{page:"western ladyfern",sci:"Athyrium filix-femina ssp. cyclosorum",x:"o"},
{page:"white nemophila",sci:"Nemophila heterophylla",x:"o"},
{page:"wood ferns",sci:"Dryopteris spp.",x:"k"},
{page:"afro-australian daisies",sci:"Dimorphotheca spp.",x:"k"},
{page:"alderney crane's-bill",sci:"Geranium core-core",x:"o"},
{page:"american red elder",sci:"Sambucus racemosa ssp. racemosa",x:"o"},
{page:"american wild carrot",sci:"Daucus pusillus",x:"o"},
{page:"Araceae",com:"aroid family",sci:"family Araceae",x:"f"},
{page:"Asphodelaceae",com:"asphodel family",sci:"family Asphodelaceae",x:"f"},
{page:"Balsaminaceae",com:"balsam family",sci:"family Balsaminaceae",x:"f"},
{page:"belladonna lily",sci:"Amaryllis belladonna",x:"o"},
{page:"Campanulaceae",com:"bellflower family",sci:"family Campanulaceae",x:"f"},
{page:"bitter lettuce",sci:"Lactuca virosa",x:"o"},
{page:"blue oak",sci:"Quercus douglasii",x:"o"},
{page:"Bolboschoenus",sci:"Bolboschoenus spp.",x:"k"},
{page:"bowltube iris",sci:"Iris macrosiphon",x:"o"},
{page:"Dennstaedtiaceae",com:"bracken family",sci:"family Dennstaedtiaceae",x:"f"},
{page:"brass buttons",sci:"Cotula coronopifolia",x:"o"},
{page:"broadleaved pepperweed",sci:"Lepidium latifolium",x:"o"},
{page:"bromes",sci:"Bromus spp.",x:"k"},
{page:"bull clover",sci:"Trifolium fucatum",x:"o"},
{page:"bull mallow",sci:"Malva nicaeensis",x:"o"},
{page:"bunchleaf penstemon",sci:"Penstemon heterophyllus",x:"o"},
{page:"buttons",sci:"Cotula spp.",x:"k"},
{page:"california aster",sci:"Corethrogyne filaginifolia",x:"o"},
{page:"california buckwheat",sci:"Eriogonum fasciculatum",x:"o"},
{page:"california goldenbanner",sci:"Thermopsis californica",x:"o"},
{page:"california goldenbush",sci:"Ericameria ericoides",x:"o"},
{page:"california harebell",sci:"Campanula prenanthoides",x:"o"},
{page:"california larkspur",sci:"Delphinium californicum",x:"o"},
{page:"california loosestrife",sci:"Lythrum californicum",x:"o"},
{page:"california milkweed",sci:"Asclepias californica",x:"o"},
{page:"calla lily",sci:"Zantedeschia aethiopica",x:"o"},
{page:"canyon gooseberry",sci:"Ribes menziesii",x:"o"},
{page:"carrots",sci:"Daucus spp.",x:"k"},
{page:"chaparral clarkia",sci:"Clarkia affinis",x:"o"},
{page:"chaparral currant",sci:"Ribes malvaceum",x:"o"},
{page:"chestnuts",sci:"Castanea spp.",x:"o"},
{page:"Clarkia concinna concinna",sci:"Clarkia concinna ssp. concinna",x:"o"},
{page:"clustered dock",sci:"Rumex conglomeratus",x:"o"},
{page:"coast range agoseris",sci:"Agoseris hirsuta",x:"o"},
{page:"coastal brookfoam",sci:"Boykinia occidentalis",x:"o"},
{page:"coastal burnweed",sci:"Senecio minimus",x:"o"},
{page:"coffeeberry",sci:"Frangula californica",x:"o"},
{page:"common ivy",sci:"Hedera helix",x:"o"},
{page:"common manzanita",sci:"Arctostaphylos manzanita",x:"o"},
{page:"common silverweed",sci:"Potentilla anserina",x:"o"},
{page:"common sow-thistle",sci:"Sonchus oleraceus",x:"o"},
{page:"common st. john's-wort",sci:"Hypericum perforatum",x:"o"},
{page:"congdon's monkeyflower",sci:"Diplacus congdonii",x:"o"},
{page:"cottonbatting plant",sci:"Pseudognaphalium stramineum",x:"o"},
{page:"cream sacs",sci:"Castilleja rubicundula ssp. lithospermoides",x:"o"},
{page:"creeping snowberry",sci:"Symphoricarpos mollis",x:"o"},
{page:"crimson clover",sci:"Trifolium incarnatum",x:"o"},
{page:"distant phacelia",sci:"Phacelia distans",x:"o"},
{page:"dodders",sci:"Cuscuta spp.",x:"k"},
{page:"douglas' meadowfoam",sci:"Limnanthes douglasii",x:"o"},
{page:"dwarf popcornflower",sci:"Plagiobothrys humistratus",x:"o"},
{page:"fairybells",sci:"Prosartes spp.",x:"k"},
{page:"fewflower blue-eyed mary",sci:"Collinsia sparsiflora",x:"o"},
{page:"field marigold",sci:"Calendula arvensis",x:"o"},
{page:"five-finger fern",sci:"Adiantum aleuticum",x:"o"},
{page:"fogfruits",sci:"Phyla spp.",x:"k"},
{page:"foothill larkspur",sci:"Delphinium hesperium",x:"o"},
{page:"fountain thistle",sci:"Cirsium fontinale",x:"k"},
{page:"fragrant fritillary",sci:"Fritillaria liliacea",x:"o"},
{page:"gambel's milkvetch",sci:"Astragalus gambelianus",x:"o"},
{page:"goldback fern",sci:"Pentagramma triangularis",x:"o"},
{page:"graceful bedstraw",sci:"Galium porrigens",x:"o"},
{page:"grassy tarweed",sci:"Madia gracilis",x:"o"},
{page:"great valley gumweed",sci:"Grindelia camporum",x:"o"},
{page:"ground rose",sci:"Rosa spithamea",x:"o"},
{page:"groundsels",sci:"Senecio spp.",x:"k"},
{page:"hairy bittercress",sci:"Cardamine hirsuta",x:"o"},
{page:"hairy brackenfern",sci:"Pteridium aquilinum var. pubescens",x:"o"},
{page:"henderson's angelica",sci:"Angelica hendersonii",x:"o"},
{page:"Holocarpha",sci:"Holocarpha spp.",x:"k"},
{page:"hooker's fairybells",sci:"Prosartes hookeri",x:"o"},
{page:"ivies",sci:"Hedera spp.",x:"k"},
{page:"kashmir balsam",sci:"Impatiens balfourii",x:"o"},
{page:"large-flowered leptosiphon",sci:"Leptosiphon grandiflorus",x:"o"},
{page:"leafless wintergreen",sci:"Pyrola aphylla",x:"o"},
{page:"lemon balm",sci:"Melissa officinalis",x:"o"},
{page:"little-robin",sci:"Geranium purpureum",x:"o"},
{page:"longspur seablush",sci:"Plectritis ciliosa",x:"o"},
{page:"Lythraceae",com:"lythrum family",sci:"family Lythraceae",x:"f"},
{page:"marigolds",sci:"Calendula spp.",x:"k"},
{page:"Limnanthaceae",com:"meadowfoam family",sci:"family Limnanthaceae",x:"f"},
{page:"mexicali onion",sci:"Allium peninsulare",x:"o"},
{page:"Microseris acuminata",x:"o"},
{page:"mission prickly-pear",sci:"Opuntia ficus-indica",x:"o"},
{page:"monterey indian paintbrush",sci:"Castilleja latifolia",x:"o"},
{page:"mount hamilton fountain thistle",sci:"Cirsium fontinale var. campylon",x:"o"},
{page:"mountain dandelions",sci:"Agoseris spp.",x:"k"},
{page:"naked buckwheat",sci:"Eriogonum nudum",x:"o"},
{page:"north californian indian pink",sci:"Silene laciniata ssp. californica",x:"o"},
{page:"oregon gumplant",sci:"Grindelia stricta",x:"o"},
{page:"pacific false bindweed",sci:"Calystegia purpurata ssp. purpurata",x:"o"},
{page:"pale pink-sorrel",sci:"Oxalis incarnata",x:"o"},
{page:"pallid manzanita",sci:"Arctostaphylos pallida",x:"o"},
{page:"passionflowers",sci:"Passiflora spp.",x:"k"},
{page:"Passifloraceae",com:"passionfruit family",sci:"family Passifloraceae",x:"f"},
{page:"pennyroyal",sci:"Mentha pulegium",x:"o"},
{page:"pit-gland tarweed",sci:"Holocarpha virgata",x:"o"},
{page:"poison sanicle",sci:"Sanicula bipinnata",x:"o"},
{page:"purple foxglove",sci:"Digitalis purpurea",x:"o"},
{page:"pussy-ears",sci:"Calochortus tolmiei",x:"o"},
{page:"red brome",sci:"Bromus rubens",x:"o"},
{page:"red hot poker",sci:"Kniphofia uvaria",x:"o"},
{page:"red passionflower",sci:"Passiflora manicata",x:"o"},
{page:"red valerian",sci:"Centranthus ruber",x:"o"},
{page:"red-berried elder",sci:"Sambucus racemosa",x:"k"},
{page:"reddish tufted vetch",sci:"Vicia benghalensis",x:"o"},
{page:"redwood violet",sci:"Viola sempervirens",x:"o"},
{page:"rod wirelettuce",sci:"Stephanomeria virgata",x:"o"},
{page:"rosy sandcrocus",sci:"Romulea rosea",x:"o"},
{page:"rough-fruited buttercup",sci:"Ranunculus muricatus",x:"o"},
{page:"san francisco collinsia",sci:"Collinsia multicolor",x:"o"},
{page:"san francisco wallflower",sci:"Erysimum franciscanum",x:"o"},
{page:"scarlet monkeyflower",sci:"Erythranthe cardinalis",x:"o"},
{page:"sea fig",sci:"Carpobrotus edulis",x:"o"},
{page:"Cyperaceae",com:"sedges",sci:"family Cyperaceae",x:"f"},
{page:"serpentine leptosiphon",sci:"Leptosiphon ambiguus",x:"o"},
{page:"shasta daisy",sci:"Leucanthemum maximum",x:"o"},
{page:"shepherd's-needle",sci:"Scandix pecten-veneris",x:"o"},
{page:"sky lupine",sci:"Lupinus nanus",x:"o"},
{page:"slender phlox",sci:"Microsteris gracilis",x:"o"},
{page:"smooth cat's ear",sci:"Hypochaeris glabra",x:"o"},
{page:"smooth tare",sci:"Vicia tetrasperma",x:"o"},
{page:"spotted coralroot",sci:"Corallorhiza maculata",x:"o"},
{page:"spotted medick",sci:"Medicago arabica",x:"o"},
{page:"st john's worts",sci:"Hypericum spp.",x:"k"},
{page:"Hypericaceae",com:"st. john's wort family",sci:"family Hypericaceae",x:"f"},
{page:"Celastraceae",com:"staff-vine family",sci:"family Celastraceae",x:"f"},
{page:"star-flowered lily-of-the-valley",sci:"Maianthemum stellatum",x:"o"},
{page:"sticky snakeroot",sci:"Ageratina adenophora",x:"o"},
{page:"stinging lupine",sci:"Lupinus hirsutissimus",x:"o"},
{page:"striped coralroot",sci:"Corallorhiza striata",x:"o"},
{page:"striped treasureflower",sci:"Gazania linearis",x:"o"},
{page:"sweet alyssum",sci:"Lobularia maritima",x:"o"},
{page:"sweet scabious",sci:"Sixalix atropurpurea",x:"o"},
{page:"trailing african daisy",sci:"Dimorphotheca fruticosa",x:"o"},
{page:"tree clover",sci:"Trifolium ciliolatum",x:"o"},
{page:"tufted poppy",sci:"Eschscholzia caespitosa",x:"o"},
{page:"turkey tangle frogfruit",sci:"Phyla nodiflora",x:"o"},
{page:"twinberry honeysuckle",sci:"Lonicera involucrata",x:"o"},
{page:"valley oak",sci:"Quercus lobata",x:"o"},
{page:"water primrose",sci:"Ludwigia hexapetala",x:"o"},
{page:"western burning bush",sci:"Euonymus occidentalis",x:"o"},
{page:"western wallflower",sci:"Erysimum capitatum",x:"o"},
{page:"white blue-eyed mary",sci:"Collinsia bartsiifolia",x:"o"},
{page:"white brodiaea",sci:"Triteleia hyacinthina",x:"o"},
{page:"white clover",sci:"Trifolium repens",x:"o"},
{page:"wight's paint brush",sci:"Castilleja wightii",x:"o"},
{page:"wild mustard",sci:"Sinapis arvensis",x:"o"},
{page:"wind poppy",sci:"Papaver heterophyllum",x:"o"},
{page:"wirelettuce",sci:"Stephanomeria spp.",x:"k"},
{page:"woollypod milkweed",sci:"Asclepias eriocarpa",x:"o"},
{page:"yellow glandweed",sci:"Bellardia viscosa",x:"o"},
{page:"yellow salsify",sci:"Tragopogon dubius",x:"o"},
{page:"Acmispon argophyllus",x:"u"},
{page:"Acmispon argyraeus",x:"u"},
{page:"Acmispon micranthus",x:"u"},
{page:"alameda thistle",sci:"Cirsium quercetorum",x:"u"},
{page:"alfalfa",sci:"Medicago sativa",x:"u"},
{page:"alkali centaury",sci:"Zeltnera trichantha",x:"u"},
{page:"alkali desertparsley",sci:"Lomatium caruifolium var. caruifolium",x:"u"},
{page:"alkali mariposa lily",sci:"Calochortus striatus",x:"u"},
{page:"alkali pepperweed",sci:"Lepidium dictyotum",x:"u"},
{page:"alsike clover",sci:"Trifolium hybridum",x:"u"},
{page:"american brooklime",sci:"Veronica americana",x:"u"},
{page:"american dogwood",sci:"Cornus sericea ssp. sericea",x:"u"},
{page:"angled pea",sci:"Lathyrus angulatus",x:"u"},
{page:"anglestem buckwheat",sci:"Eriogonum angulosum",x:"u"},
{page:"annual checkerbloom",sci:"Sidalcea calycosa",x:"u"},
{page:"annual false dandelion",sci:"Agoseris heterophylla var. heterophylla",x:"u"},
{page:"annual saltmarsh aster",sci:"Symphyotrichum subulatum",x:"u"},
{page:"arrowleaf clover",sci:"Trifolium vesiculosum",x:"u"},
{page:"Asclepias speciosa",x:"u"},
{page:"Asclepias vestita",x:"u"},
{page:"ashy silktassel",sci:"Garrya flavescens",x:"u"},
{page:"australian brome",sci:"Bromus arenarius",x:"u"},
{page:"australian waterbuttons",sci:"Cotula australis",x:"u"},
{page:"bachelor's-button",sci:"Centaurea cyanus",x:"u"},
{page:"bald brome",sci:"Bromus racemosus",x:"u"},
{page:"banana passionfruit",sci:"Passiflora tarminiana",x:"o"},
{page:"barestem biscuitroot",sci:"Lomatium nudicaule",x:"u"},
{page:"barren brome",sci:"Bromus sterilis",x:"u"},
{page:"bay forget-me-not",sci:"Myosotis laxa",x:"u"},
{page:"beach tidytips",sci:"Layia carnosa",x:"u"},
{page:"beach wormwood",sci:"Artemisia pycnocephala",x:"u"},
{page:"bearded clover",sci:"Trifolium barbigerum",x:"u"},
{page:"bearded iris",sci:"Iris germanica",x:"u"},
{page:"bentham's broom",sci:"Acmispon cytisoides",x:"u"},
{page:"biennial wormwood",sci:"Artemisia biennis",x:"u"},
{page:"big pod lupine",sci:"Lupinus pachylobus",x:"u"},
{page:"bigelow's sneezeweed",sci:"Helenium bigelovii",x:"o"},
{page:"bigflower agoseris",sci:"Agoseris grandiflora var. grandiflora",x:"u"},
{page:"bigseed biscuitfruit",sci:"Lomatium macrocarpum",x:"u"},
{page:"black maidenhair fern",sci:"Adiantum capillus-veneris",x:"u"},
{page:"black medick",sci:"Medicago lupulina",x:"u"},
{page:"black wattle",sci:"Acacia mearnsii",x:"o"},
{page:"blue-and-white daisybush",sci:"Dimorphotheca ecklonis",x:"u"},
{page:"bluecrown passionflower",sci:"Passiflora caerulea",x:"u"},
{page:"bluehead gilia",sci:"Gilia capitata",x:"u"},
{page:"bog st. john's-wort",sci:"Hypericum anagalloides",x:"u"},
{page:"bollean mistletoe",sci:"Phoradendron bolleanum",x:"u"},
{page:"branching indian clover",sci:"Trifolium dichotomum",x:"u"},
{page:"bristly fiddleneck",sci:"Amsinckia tessellata",x:"u"},
{page:"broad-leaved dock",sci:"Rumex obtusifolius",x:"u"},
{page:"broadleaf lupine",sci:"Lupinus latifolius",x:"u"},
{page:"broadtooth monkeyflower",sci:"Erythranthe latidens",x:"u"},
{page:"brown dogwood",sci:"Cornus glabrata",x:"u"},
{page:"brown mustard",sci:"Brassica juncea",x:"u"},
{page:"brownies",sci:"Diplacus douglasii",x:"u"},
{page:"buck's-horn plantain",sci:"Plantago coronopus",x:"u"},
{page:"bugle hedgenettle",sci:"Stachys ajugoides",x:"u"},
{page:"bush chinquapin",sci:"Chrysolepis sempervirens",x:"u"},
{page:"bush tanoak",sci:"Notholithocarpus densiflorus var. echinoides",x:"u"},
{page:"butter lupine",sci:"Lupinus luteolus",x:"u"},
{page:"button medick",sci:"Medicago orbicularis",x:"u"},
{page:"cabbage",sci:"Brassica oleracea",x:"u"},
{page:"california bedstraw",sci:"Galium californicum ssp. californicum",x:"u"},
{page:"california brome",sci:"Bromus carinatus",x:"u"},
{page:"california centaury",sci:"Zeltnera venusta",x:"u"},
{page:"california dock",sci:"Rumex californicus",x:"u"},
{page:"Cuscuta californica",com:"california dodder",x:"u"},
{page:"Cuscuta occidentalis",com:"california dodder",x:"u"},
{page:"california groundsel",sci:"Senecio aphanactis",x:"u"},
{page:"california lomatium",sci:"Lomatium californicum",x:"u"},
{page:"california mugwort",sci:"Artemisia douglasiana",x:"u"},
{page:"california shield fern",sci:"Polystichum californicum",x:"u"},
{page:"cambria morning-glory",sci:"Calystegia subacaulis ssp. episcopalis",x:"u"},
{page:"canary island geranium",sci:"Geranium palmatum",x:"u"},
{page:"canary island st. john's wort",sci:"Hypericum canariense",x:"u"},
{page:"canary islands ivy",sci:"Hedera canariensis",x:"u"},
{page:"canyon clarkia",sci:"Clarkia epilobioides",x:"u"},
{page:"canyon dodder",sci:"Cuscuta subinclusa",x:"u"},
{page:"canyon live oak",sci:"Quercus chrysolepis",x:"u"},
{page:"cape marigold",sci:"Dimorphotheca sinuata",x:"u"},
{page:"carolina crane's-bill",sci:"Geranium carolinianum",x:"u"},
{page:"Ceanothus jepsonii",x:"u"},
{page:"Centaurea benedicta",x:"u"},
{page:"Centaurea cineraria",x:"u"},
{page:"Centaurea diffusa",x:"u"},
{page:"Centaurea diluta",x:"u"},
{page:"Centaurea jacea",x:"u"},
{page:"Centaurium",com:"centauries",sci:"Centaurium spp.",x:"k"},
{page:"central coast iris",sci:"Iris longipetala",x:"u"},
{page:"chaffweed",sci:"Lysimachia minima",x:"u"},
{page:"chamisso bush lupine",sci:"Lupinus chamissonis",x:"u"},
{page:"changing forget-me-not",sci:"Myosotis discolor",x:"u"},
{page:"chaparral bird's-foot trefoil",sci:"Acmispon grandiflorus var. grandiflorus",x:"u"},
{page:"chaparral honeysuckle",sci:"Lonicera interrupta",x:"u"},
{page:"chaparral silktassel",sci:"Garrya congdonii",x:"u"},
{page:"chaparral whitethorn",sci:"Ceanothus leucodermis",x:"u"},
{page:"cheatgrass",sci:"Bromus tectorum",x:"u"},
{page:"cheeseweed mallow",sci:"Malva parviflora",x:"u"},
{page:"chilean chess",sci:"Bromus berteroanus",x:"u"},
{page:"chilean plantain",sci:"Plantago truncata ssp. firma",x:"u"},
{page:"chinook brome",sci:"Bromus laevipes",x:"u"},
{page:"chocolate lily",sci:"Fritillaria biflora",x:"u"},
{page:"Chrysolepis chrysophylla chrysophylla",sci:"Chrysolepis chrysophylla var. chrysophylla",x:"u"},
{page:"Chrysolepis chrysophylla minor",sci:"Chrysolepis chrysophylla var. minor",x:"u"},
{page:"cinquefoil geranium",sci:"Geranium potentilloides",x:"u"},
{page:"clammy clover",sci:"Trifolium obtusiflorum",x:"u"},
{page:"Clarkia amoena amoena",sci:"Clarkia amoena ssp. amoena",x:"u"},
{page:"Clarkia amoena huntiana",sci:"Clarkia amoena ssp. huntiana",x:"u"},
{page:"Clarkia purpurea purpurea",sci:"Clarkia purpurea ssp. purpurea",x:"u"},
{page:"Clarkia purpurea viminea",sci:"Clarkia purpurea ssp. viminea",x:"u"},
{page:"clay buckwheat",sci:"Eriogonum argillosum",x:"u"},
{page:"Clematis pauciflora",x:"u"},
{page:"coast goldenrod",sci:"Solidago spathulata",x:"u"},
{page:"coast oak",sci:"Quercus parvula",x:"u"},
{page:"Calystegia collina",com:"coast range false bindweed",x:"k"},
{page:"coast range false bindweed",sci:"Calystegia collina ssp. collina",x:"u"},
{page:"coast range triteleia",sci:"Triteleia lugens",x:"u"},
{page:"coast whitethorn",sci:"Ceanothus incanus",x:"u"},
{page:"coastal bird's-foot trefoil",sci:"Acmispon maritimus var. maritimus",x:"u"},
{page:"coastal bluff morning-glory",sci:"Calystegia purpurata ssp. saxicola",x:"u"},
{page:"coastal goldfields",sci:"Lasthenia minor",x:"u"},
{page:"coastal hedge-nettle",sci:"Stachys chamissonis",x:"u"},
{page:"coastal monkeyflower",sci:"Erythranthe dentata",x:"u"},
{page:"coastal plantain",sci:"Plantago elongata",x:"u"},
{page:"coastal silverpuffs",sci:"Microseris bigelovii",x:"u"},
{page:"coastal wild buckwheat",sci:"Eriogonum cinereum",x:"u"},
{page:"cobwebby thistle",sci:"Cirsium occidentale var. occidentale",x:"u"},
{page:"collared annual lupine",sci:"Lupinus truncatus",x:"u"},
{page:"colorado desert wild buckwheat",sci:"Eriogonum deserticola",x:"u"},
{page:"columbia brome",sci:"Bromus vulgaris",x:"u"},
{page:"common goldfields",sci:"Lasthenia gracilis",x:"u"},
{page:"common groundsel",sci:"Senecio vulgaris",x:"u"},
{page:"common mallow",sci:"Malva sylvestris",x:"u"},
{page:"common mugwort",sci:"Artemisia vulgaris",x:"u"},
{page:"common soft-brome",sci:"Bromus hordeaceus",x:"u"},
{page:"compact brome",sci:"Bromus madritensis",x:"u"},
{page:"contra costa goldfields",sci:"Lasthenia conjugens",x:"u"},
{page:"cook's triteleia",sci:"Triteleia ixioides ssp. cookii",x:"u"},
{page:"corn chamomile",sci:"Anthemis arvensis",x:"u"},
{page:"corn cleavers",sci:"Galium tricornutum",x:"u"},
{page:"coulter pine",sci:"Pinus coulteri",x:"u"},
{page:"coville's buckwheat",sci:"Eriogonum covilleanum",x:"u"},
{page:"coyote ceanothus",sci:"Ceanothus ferrisiae",x:"u"},
{page:"creeping thistle",sci:"Cirsium arvense",x:"u"},
{page:"creeping woodsorrel",sci:"Oxalis corniculata",x:"u"},
{page:"cretan tree-mallow",sci:"Malva multiflora",x:"u"},
{page:"crown brodiaea",sci:"Brodiaea coronaria",x:"u"},
{page:"crystal springs fountain thistle",sci:"Cirsium fontinale var. fontinale",x:"u"},
{page:"cutleaf burnweed",sci:"Senecio glomeratus",x:"u"},
{page:"davy's clarkia",sci:"Clarkia davyi",x:"u"},
{page:"deerbrush ceanothus",sci:"Ceanothus integerrimus var. integerrimus",x:"u"},
{page:"deerpea vetch",sci:"Vicia ludoviciana ssp. ludoviciana",x:"u"},
{page:"delta tule pea",sci:"Lathyrus jepsonii",x:"u"},
{page:"desert plantain",sci:"Plantago ovata",x:"u"},
{page:"diamond clarkia",sci:"Clarkia rhomboidea",x:"u"},
{page:"diamond-petaled california poppy",sci:"Eschscholzia rhombipetala",x:"u"},
{page:"diogenes' lantern",sci:"Calochortus amabilis",x:"u"},
{page:"dog-rose",sci:"Rosa canina",x:"u"},
{page:"double-head clover",sci:"Trifolium macraei",x:"u"},
{page:"douglas' violet",sci:"Viola douglasii",x:"u"},
{page:"douglas's aster",sci:"Symphyotrichum subspicatum",x:"u"},
{page:"dudley's shield fern",sci:"Polystichum dudleyi",x:"u"},
{page:"dwarf bilberry",sci:"Vaccinium cespitosum",x:"u"},
{page:"dwarf mallow",sci:"Malva neglecta",x:"u"},
{page:"dwarf nettle",sci:"Urtica urens",x:"u"},
{page:"eastern beaked hazel",sci:"Corylus cornuta ssp. cornuta",x:"u"},
{page:"eastwood's nemophila",sci:"Nemophila pulchella",x:"u"},
{page:"eldorado larkspur",sci:"Delphinium hansenii",x:"u"},
{page:"elegant wild buckwheat",sci:"Eriogonum elegans",x:"u"},
{page:"entire-leaved cotoneaster",sci:"Cotoneaster integrifolius",x:"u"},
{page:"Epilobium campestre",x:"u"},
{page:"Epilobium densiflorum",x:"u"},
{page:"Epilobium foliosum",x:"u"},
{page:"Epilobium hallanum",x:"u"},
{page:"Epilobium minutum",x:"u"},
{page:"Epilobium torreyi",x:"u"},
{page:"Erythranthe grandis",x:"u"},
{page:"eurasian sweet violet",sci:"Viola odorata",x:"u"},
{page:"fairy fans",sci:"Clarkia breweri",x:"u"},
{page:"farewell to spring",sci:"Clarkia amoena",x:"k"},
{page:"feltleaf everlasting",sci:"Pseudognaphalium microcephalum",x:"u"},
{page:"few-flowered clover",sci:"Trifolium oliganthum",x:"u"},
{page:"field dodder",sci:"Cuscuta campestris",x:"u"},
{page:"field horsetail",sci:"Equisetum arvense",x:"u"},
{page:"field peppergrass",sci:"Lepidium campestre",x:"u"},
{page:"five angled dodder",sci:"Cuscuta pentagona",x:"u"},
{page:"flax-leaved horseweed",sci:"Erigeron bonariensis",x:"u"},
{page:"fleshy lupine",sci:"Lupinus affinis",x:"u"},
{page:"foothill deervetch",sci:"Acmispon brachycarpus",x:"u"},
{page:"footsteps of spring",sci:"Sanicula arctopoides",x:"u"},
{page:"forest red gum",sci:"Eucalyptus tereticornis",x:"u"},
{page:"forked nightshade",sci:"Solanum furcatum",x:"u"},
{page:"fragrant bedstraw",sci:"Galium triflorum",x:"u"},
{page:"fragrant everlasting",sci:"Pseudognaphalium beneolens",x:"u"},
{page:"franchet's cotoneaster",sci:"Cotoneaster franchetii",x:"u"},
{page:"franciscan thistle",sci:"Cirsium andrewsii",x:"u"},
{page:"fringed brome",sci:"Bromus ciliatus",x:"u"},
{page:"fremont's silktassel",sci:"Garrya fremontii",x:"u"},
{page:"fuller's teasel",sci:"Dipsacus fullonum",x:"u"},
{page:"german chamomile",sci:"Matricaria chamomilla",x:"u"},
{page:"giant vetch",sci:"Vicia gigantea",x:"u"},
{page:"giant white wakerobin",sci:"Trillium albidum",x:"u"},
{page:"golden dock",sci:"Rumex fueginus",x:"u"},
{page:"golden-carpet wild buckwheat",sci:"Eriogonum luteolum var. luteolum",x:"u"},
{page:"golden-eyed grass",sci:"Sisyrinchium californicum",x:"u"},
{page:"goldenthread",sci:"Cuscuta pacifica var. pacifica",x:"u"},
{page:"goldwire",sci:"Hypericum concinnum",x:"u"},
{page:"goosefoot violet",sci:"Viola purpurea",x:"u"},
{page:"grass pea",sci:"Lathyrus sphaericus",x:"u"},
{page:"grasspea",sci:"Lathyrus sativus",x:"u"},
{page:"gray pine",sci:"Pinus sabiniana",x:"u"},
{page:"gray's clover",sci:"Trifolium grayi",x:"u"},
{page:"Equisetum telmateia telmateia",com:"great horsetail",sci:"Equisetum telmateia ssp. telmateia",x:"u"},
{page:"greater plantain",sci:"Plantago major",x:"u"},
{page:"hairy nightshade",sci:"Solanum physalifolium var. nitidibaccatum",x:"u"},
{page:"hairy vetchling",sci:"Lathyrus hirsutus",x:"u"},
{page:"hairy woodsorrel",sci:"Oxalis pilosa",x:"u"},
{page:"hairy-flower wild buckwheat",sci:"Eriogonum hirtiflorum",x:"u"},
{page:"hairy-pitted stork's-bill",sci:"Erodium brachycarpum",x:"u"},
{page:"hasse vetch",sci:"Vicia hassei",x:"u"},
{page:"heart-podded hoary cress",sci:"Lepidium draba",x:"u"},
{page:"heath groundsel",sci:"Senecio sylvaticus",x:"u"},
{page:"hedge bedstraw",sci:"Galium mollugo",x:"u"},
{page:"heermann's lotus",sci:"Acmispon heermannii",x:"u"},
{page:"heermann's tarweed",sci:"Holocarpha heermannii",x:"u"},
{page:"Heliotropium europaeum",x:"u"},
{page:"hoary nettle",sci:"Urtica dioica ssp. holosericea",x:"u"},
{page:"hoary wild buckwheat",sci:"Eriogonum saxatile",x:"u"},
{page:"hoffmann's sanicle",sci:"Sanicula hoffmannii",x:"u"},
{page:"Holocarpha macradenia",x:"u"},
{page:"Holocarpha obconica",x:"u"},
{page:"Holodiscus discolor discolor",sci:"Holodiscus discolor var discolor",x:"u"},
{page:"Holodiscus discolor glabrescens",sci:"Holodiscus discolor var glabrescens",x:"u"},
{page:"horseweed",sci:"Erigeron canadensis",x:"u"},
{page:"Hypericum grandifolium",x:"u"},
{page:"iberian star-thistle",sci:"Centaurea iberica",x:"u"},
{page:"interior live oak",sci:"Quercus wislizeni",x:"u"},
{page:"island mallow",sci:"Malva assurgentiflora",x:"u"},
{page:"italian hawksbeard",sci:"Crepis bursifolia",x:"u"},
{page:"japanese honeysuckle",sci:"Lonicera japonica",x:"o"},
{page:"jepson's woolly sunflower",sci:"Eriophyllum jepsonii",x:"u"},
{page:"jersey cudweed",sci:"Pseudognaphalium luteoalbum",x:"u"},
{page:"johnston's honeysuckle",sci:"Lonicera subspicata var. denudata",x:"u"},
{page:"jointed charlock",sci:"Raphanus raphanistrum",x:"u"},
{page:"juniper mistletoe",sci:"Phoradendron juniperinum",x:"u"},
{page:"knobcone pine",sci:"Pinus attenuata",x:"u"},
{page:"knotted clover",sci:"Trifolium striatum",x:"u"},
{page:"laceleaf sanicle",sci:"Sanicula laciniata",x:"u"},
{page:"lamarck's bedstraw",sci:"Galium divaricatum",x:"u"},
{page:"lanceleaf frogfruit",sci:"Phyla lanceolata",x:"u"},
{page:"large-head clover",sci:"Trifolium macrocephalum",x:"u"},
{page:"large-leaved lupine",sci:"Lupinus polyphyllus var. polyphyllus",x:"u"},
{page:"largeflower fairybells",sci:"Prosartes smithii",x:"u"},
{page:"leafy flebane",sci:"Erigeron foliosus",x:"u"},
{page:"leather oak",sci:"Quercus durata",x:"u"},
{page:"lens-podded hoary cress",sci:"Lepidium chalepense",x:"u"},
{page:"lesser periwinkle",sci:"Vinca minor",x:"u"},
{page:"lesser swine-cress",sci:"Lepidium didymum",x:"u"},
{page:"little western bittercress",sci:"Cardamine oligosperma",x:"u"},
{page:"long-rayed brodiaea",sci:"Triteleia peduncularis",x:"u"},
{page:"long-stemmed buckwheat",sci:"Eriogonum elongatum var. elongatum",x:"u"},
{page:"Madia citriodora",x:"u"},
{page:"maiden blue-eyed mary",sci:"Collinsia parviflora",x:"u"},
{page:"male fern",sci:"Dryopteris filix-mas",x:"u"},
{page:"manna gum",sci:"Eucalyptus viminalis",x:"u"},
{page:"maple-leaved checkerbloom",sci:"Sidalcea malachroides",x:"u"},
{page:"marin checkerbloom",sci:"Sidalcea hickmanii ssp. viridis",x:"u"},
{page:"maritime goldfields",sci:"Lasthenia maritima",x:"u"},
{page:"marsh baccharis",sci:"Baccharis glutinosa",x:"u"},
{page:"marsh horsetail",sci:"Equisetum palustre",x:"u"},
{page:"marsh microseris",sci:"Microseris paludosa",x:"u"},
{page:"marsh morning glory",sci:"Calystegia sepium ssp. limnophila",x:"u"},
{page:"mason's ceanothus",sci:"Ceanothus masonii",x:"u"},
{page:"meadow nemophila",sci:"Nemophila pedunculata",x:"u"},
{page:"Microseris elegans",x:"u"},
{page:"monterey mariposa lily",sci:"Calochortus uniflorus",x:"u"},
{page:"monterey pine",sci:"Pinus radiata",x:"o"},
{page:"mount diablo buckwheat",sci:"Eriogonum truncatum",x:"u"},
{page:"mount diablo cottonseed",sci:"Micropus amphibolus",x:"u"},
{page:"mount diablo fairy-lantern",sci:"Calochortus pulchellus",x:"u"},
{page:"mount hamilton lomatium",sci:"Lomatium observatorium",x:"u"},
{page:"mount saint helena morning-glory",sci:"Calystegia collina ssp. oxyphylla",x:"u"},
{page:"mount tamalpais thistle",sci:"Cirsium hydrophilum var. vaseyi",x:"u"},
{page:"mountain coyote mint",sci:"Monardella odoratissima",x:"o"},
{page:"mountain fringepod",sci:"Thysanocarpus laciniatus",x:"u"},
{page:"mule fat",sci:"Baccharis salicifolia ssp. salicifolia",x:"u"},
{page:"musk thistle",sci:"Carduus nutans",x:"u"},
{page:"muskflower",sci:"Erythranthe moschata",x:"u"},
{page:"narrow leaved rayless fleabane",sci:"Erigeron reductus var. angustatus",x:"u"},
{page:"narrow-leaf bird's-foot trefoil",sci:"Lotus tenuis",x:"u"},
{page:"narrow-leaved cattail",sci:"Typha angustifolia",x:"u"},
{page:"narrow-leaved vetch",sci:"Vicia sativa ssp. nigra",x:"u"},
{page:"narrowleaf goldenbush",sci:"Ericameria linearifolia",x:"u"},
{page:"narrowleaf sword fern",sci:"Polystichum imbricans",x:"u"},
{page:"net pepper grass",sci:"Lepidium acutidens",x:"u"},
{page:"new zealand geranium",sci:"Geranium retrorsum",x:"u"},
{page:"new zealand nightshade",sci:"Solanum aviculare",x:"u"},
{page:"nodding clover",sci:"Trifolium cernuum",x:"u"},
{page:"northern banana passionfruit",sci:"Passiflora mixta",x:"u"},
{page:"northern cranesbill",sci:"Geranium bicknellii",x:"u"},
{page:"notchleaf clover",sci:"Trifolium bifidum",x:"u"},
{page:"nuttall's scrub oak",sci:"Quercus dumosa",x:"u"},
{page:"oakland mariposa lily",sci:"Calochortus umbellatus",x:"u"},
{page:"olive clover",sci:"Trifolium olivaceum",x:"u"},
{page:"oregon oak",sci:"Quercus garryana",x:"u"},
{page:"pacific coralroot",sci:"Corallorhiza mertensiana",x:"u"},
{page:"pacific dogwood",sci:"Cornus nuttallii",x:"u"},
{page:"pacific fringed thistle",sci:"Cirsium remotifolium var. odontolepis",x:"u"},
{page:"pacific grove clover",sci:"Trifolium polyodon",x:"u"},
{page:"pacific willow dock",sci:"Rumex transitorius",x:"u"},
{page:"pale goat-chicory",sci:"Agoseris glauca var. glauca",x:"u"},
{page:"peregrine thistle",sci:"Cirsium cymosum var. cymosum",x:"u"},
{page:"perennial sow thistle",sci:"Sonchus arvensis",x:"u"},
{page:"philadelphia fleabane",sci:"Erigeron philadelphicus var. philadelphicus",x:"u"},
{page:"phlox-leaved bedstraw",sci:"Galium andrewsii",x:"u"},
{page:"Pinaceae",com:"pine family",sci:"family Pinaceae",x:"f"},
{page:"pines",sci:"Pinus spp.",x:"k"},
{page:"pink everlasting",sci:"Pseudognaphalium ramosissimum",x:"u"},
{page:"pink plectritis",sci:"Plectritis congesta ssp. brachystemon",x:"u"},
{page:"pinpoint clover",sci:"Trifolium gracilentum",x:"u"},
{page:"plump seeded madia",sci:"Madia anomala",x:"u"},
{page:"point reyes ceanothus",sci:"Ceanothus gloriosus",x:"u"},
{page:"ponderosa pine",sci:"Pinus ponderosa",x:"u"},
{page:"pot marigold",sci:"Calendula officinalis",x:"u"},
{page:"presidio clarkia",sci:"Clarkia franciscana",x:"u"},
{page:"prickly lettuce",sci:"Lactuca serriola",x:"u"},
{page:"purple nightshade",sci:"Solanum xanti",x:"u"},
{page:"purple woodsorrel",sci:"Oxalis purpurea",x:"u"},
{page:"purple-stemmed monkeyflower",sci:"Erythranthe floribunda",x:"u"},
{page:"purplespot gilia",sci:"Gilia clivorum",x:"u"},
{page:"queen anne's lace",sci:"Daucus carota",x:"u"},
{page:"rabbitfoot clover",sci:"Trifolium arvense",x:"u"},
{page:"raiche's red ribbons",sci:"Clarkia concinna ssp. raichei",x:"u"},
{page:"rancheria clover",sci:"Trifolium albopurpureum",x:"u"},
{page:"Ranunculus canus",x:"u"},
{page:"Ranunculus occidentalis",x:"u"},
{page:"Ranunculus orthorhynchus",x:"u"},
{page:"Ranunculus repens",x:"u"},
{page:"rattan's monkeyflower",sci:"Diplacus rattanii",x:"u"},
{page:"rayless ragwort",sci:"Senecio aronicoides",x:"u"},
{page:"red clover",sci:"Trifolium pratense",x:"u"},
{page:"red huckleberry",sci:"Vaccinium parvifolium",x:"u"},
{page:"red ironbark",sci:"Eucalyptus sideroxylon",x:"u"},
{page:"red-purple ragwort",sci:"Senecio elegans",x:"u"},
{page:"rescue brome",sci:"Bromus catharticus",x:"u"},
{page:"reversed clover",sci:"Trifolium resupinatum",x:"u"},
{page:"ribbed fringepod",sci:"Thysanocarpus radians",x:"u"},
{page:"ripgut brome",sci:"Bromus diandrus",x:"u"},
{page:"river bulrush",sci:"Bolboschoenus fluviatilis",x:"u"},
{page:"river redbum",sci:"Eucalyptus camaldulensis",x:"u"},
{page:"rock sanicle",sci:"Sanicula saxatilis",x:"u"},
{page:"rock-loving fleabane",sci:"Erigeron petrophilus var. petrophilus",x:"u"},
{page:"rockjasmine monkeyflower",sci:"Erythranthe androsacea",x:"u"},
{page:"rocky mountain elder",sci:"Sambucus racemosa var. melanocarpa",x:"u"},
{page:"Rosa rubiginosa",x:"u"},
{page:"rose and white buckwheat",sci:"Eriogonum gracillimum",x:"u"},
{page:"rose-of-sharon",sci:"Hypericum calycinum",x:"o"},
{page:"round-leaved crane's-bill",sci:"Geranium rotundifolium",x:"u"},
{page:"rubber rabbitbrush",sci:"Ericameria nauseosa",x:"u"},
{page:"Rumex persicarioides",x:"u"},
{page:"rush broom",sci:"Acmispon junceus",x:"u"},
{page:"saline clover",sci:"Trifolium hydrophilum",x:"u"},
{page:"salmon mountains wakerobin",sci:"Trillium ovatum ssp. oettingeri",x:"u"},
{page:"salmonberry",sci:"Rubus spectabilis",x:"u"},
{page:"salt marsh dodder",sci:"Cuscuta salina",x:"u"},
{page:"salt marsh sanicle",sci:"Sanicula maritima",x:"u"},
{page:"salt-marsh owl-clover",sci:"Castilleja ambigua",x:"u"},
{page:"saltmarsh clubrush",sci:"Bolboschoenus maritimus ssp. paludosus",x:"u"},
{page:"san bernardino larkspur",sci:"Delphinium parryi",x:"u"},
{page:"san diego bedstraw",sci:"Galium nuttallii",x:"u"},
{page:"san diego pepperweed",sci:"Lepidium latipes",x:"u"},
{page:"san joaquin silverpuffs",sci:"Microseris campestris",x:"u"},
{page:"san mateo woolly sunflower",sci:"Eriophyllum latilobum",x:"u"},
{page:"sand-loving wallflower",sci:"Erysimum ammophilum",x:"u"},
{page:"santa barbara daisy",sci:"Erigeron karvinskianus",x:"o"},
{page:"santa barbara wirelettuce",sci:"Stephanomeria elata",x:"u"},
{page:"santa cruz clover",sci:"Trifolium buckwestiorum",x:"u"},
{page:"santa cruz island wild buckwheat",sci:"Eriogonum arborescens",x:"u"},
{page:"santa cruz wallflower",sci:"Erysimum teretifolium",x:"u"},
{page:"scouler's st. john's wort",sci:"Hypericum scouleri",x:"u"},
{page:"sea bindweed",sci:"Calystegia soldanella",x:"u"},
{page:"sea milkwort",sci:"Lysimachia maritima",x:"u"},
{page:"sea plantain",sci:"Plantago maritima",x:"u"},
{page:"seacliff wild buckwheat",sci:"Eriogonum parvifolium",x:"u"},
{page:"seacoast bulrush",sci:"Bolboschoenus robustus",x:"u"},
{page:"seaside agoseris",sci:"Agoseris apargioides",x:"u"},
{page:"seaside brome",sci:"Bromus maritimus",x:"u"},
{page:"seaside buckwheat",sci:"Eriogonum latifolium",x:"u"},
{page:"shaggy vetch",sci:"Vicia villosa ssp. villosa",x:"u"},
{page:"sharp-pod pepper-grass",sci:"Lepidium oxycarpum",x:"u"},
{page:"shelton's violet",sci:"Viola sheltonii",x:"u"},
{page:"short-spiked hedge nettle",sci:"Stachys pycnantha",x:"u"},
{page:"short-styled thistle",sci:"Cirsium brevistylum",x:"u"},
{page:"shortspur seablush",sci:"Plectritis congesta ssp. congesta",x:"u"},
{page:"showy golden madia",sci:"Madia radiata",x:"u"},
{page:"sicilian star-thistle",sci:"Centaurea sulphurea",x:"u"},
{page:"sierra false bindweed",sci:"Calystegia malacophylla ssp. pedicellata",x:"u"},
{page:"silky beach pea",sci:"Lathyrus littoralis",x:"u"},
{page:"silver dollar gum",sci:"Eucalyptus polyanthemos",x:"u"},
{page:"silverleaf cotoneaster",sci:"Cotoneaster pannosus",x:"u"},
{page:"silverleaf nightshade",sci:"Solanum elaeagnifolium",x:"u"},
{page:"slender buckwheat",sci:"Eriogonum gracile",x:"u"},
{page:"slender centaury",sci:"Centaurium tenuiflorum",x:"u"},
{page:"slender clarkia",sci:"Clarkia gracilis",x:"u"},
{page:"slender sowthistle",sci:"Sonchus tenerrimus",x:"u"},
{page:"slender stinging nettle",sci:"Urtica dioica ssp. gracilis",x:"u"},
{page:"slender thistle",sci:"Carduus tenuiflorus",x:"u"},
{page:"small flowered nemophila",sci:"Nemophila parviflora",x:"u"},
{page:"small tarweed",sci:"Madia exigua",x:"u"},
{page:"small-flower indian-paintbrush",sci:"Castilleja minor",x:"u"},
{page:"small-flowered crane's-bill",sci:"Geranium pusillum",x:"u"},
{page:"small-flowered fiddleneck",sci:"Amsinckia menziesii var. menziesii",x:"u"},
{page:"small-headed clover",sci:"Trifolium microcephalum",x:"u"},
{page:"small-leaf cream bush",sci:"Holodiscus discolor var microphyllus",x:"u"},
{page:"small-ray goldfields",sci:"Lasthenia microglossa",x:"u"},
{page:"smooth goldfields",sci:"Lasthenia glaberrima",x:"u"},
{page:"smooth hawksbeard",sci:"Crepis capillaris",x:"u"},
{page:"smooth horsetail",sci:"Equisetum laevigatum",x:"u"},
{page:"smooth tidytips",sci:"Layia chrysanthemoides",x:"u"},
{page:"soft stork's-bill",sci:"Erodium malacoides",x:"u"},
{page:"solander's geranium",sci:"Geranium solanderi",x:"u"},
{page:"southern cattail",sci:"Typha domingensis",x:"u"},
{page:"southern goldenrod",sci:"Solidago confinis",x:"u"},
{page:"spanish clover",sci:"Acmispon americanus var. americanus",x:"u"},
{page:"spearleaf agoseris",sci:"Agoseris retrorsa",x:"u"},
{page:"splendid mariposa lily",sci:"Calochortus splendens",x:"u"},
{page:"spotted knapweed",sci:"Centaurea stoebe ssp. micranthos",x:"u"},
{page:"spreading wood fern",sci:"Dryopteris expansa",x:"u"},
{page:"springbank clover",sci:"Trifolium wormskioldii",x:"u"},
{page:"st. catherine's-lace",sci:"Eriogonum giganteum var. giganteum",x:"u"},
{page:"Stephanomeria exigua coronaria",sci:"Stephanomeria exigua ssp. coronaria",x:"u"},
{page:"sticky chinese houses",sci:"Collinsia tinctoria",x:"u"},
{page:"stinkbells",sci:"Fritillaria agrestis",x:"u"},
{page:"stinking iris",sci:"Iris foetidissima",x:"u"},
{page:"stone pine",sci:"Pinus pinea",x:"u"},
{page:"strawberry clover",sci:"Trifolium fragiferum",x:"u"},
{page:"strawberry tree",sci:"Arbutus unedo",x:"u"},
{page:"stream orchid",sci:"Epipactis gigantea",x:"u"},
{page:"strigose lotus",sci:"Acmispon strigosus",x:"u"},
{page:"subterranean clover",sci:"Trifolium subterraneum",x:"u"},
{page:"suffocated clover",sci:"Trifolium suffocatum",x:"u"},
{page:"sulfur buckwheat",sci:"Eriogonum umbellatum",x:"u"},
{page:"summer lupine",sci:"Lupinus formosus var. formosus",x:"o"},
{page:"superb mariposa lily",sci:"Calochortus superbus",x:"u"},
{page:"swamp thistle",sci:"Cirsium douglasii var. douglasii",x:"u"},
{page:"sweet pea",sci:"Lathyrus odoratus",x:"u"},
{page:"sycamore mistletoe",sci:"Phoradendron macrophyllum",x:"u"},
{page:"sylvan microseris",sci:"Microseris sylvatica",x:"u"},
{page:"Symphyotrichum lanceolatum hesperium",sci:"Symphyotrichum lanceolatum var. hesperium",x:"u"},
{page:"Symphyotrichum lentum",x:"u"},
{page:"tall blue lettuce",sci:"Lactuca biennis",x:"u"},
{page:"tall centaury",sci:"Zeltnera exaltata",x:"u"},
{page:"tall coastal plantain",sci:"Plantago subnuda",x:"u"},
{page:"tall tidytips",sci:"Layia hieracioides",x:"u"},
{page:"tangier pea",sci:"Lathyrus tingitanus",x:"u"},
{page:"tarragon",sci:"Artemisia dracunculus",x:"u"},
{page:"tarweed fiddleneck",sci:"Amsinckia lycopsoides",x:"u"},
{page:"thimble clover",sci:"Trifolium microdon",x:"u"},
{page:"thornless elmleaf blackberry",sci:"Rubus ulmifolius var. anoplothyrsus",x:"u"},
{page:"threadleaf groundsel",sci:"Senecio flaccidus",x:"u"},
{page:"three-petal bedstraw",sci:"Galium trifidum ssp. columbianum",x:"u"},
{page:"thunberg's brome",sci:"Bromus japonicus",x:"u"},
{page:"tiburon buckwheat",sci:"Eriogonum luteolum var. caninum",x:"u"},
{page:"tiburon mariposa lily",sci:"Calochortus tiburonensis",x:"u"},
{page:"tiny bedstraw",sci:"Galium murale",x:"u"},
{page:"tobacco brush",sci:"Ceanothus velutinus",x:"u"},
{page:"tocalote",sci:"Centaurea melitensis",x:"u"},
{page:"torrey pine",sci:"Pinus torreyana",x:"u"},
{page:"torrey's pea",sci:"Lathyrus torreyi",x:"u"},
{page:"tree mallow",sci:"Malva arborea",x:"u"},
{page:"Triphysaria eriantha rosea",sci:"Triphysaria eriantha ssp. rosea",x:"u"},
{page:"tropical horseweed",sci:"Erigeron sumatrensis",x:"u"},
{page:"turkey pea",sci:"Sanicula tuberosa",x:"u"},
{page:"twining snakelily",sci:"Dichelostemma volubile",x:"u"},
{page:"two-color rabbit tobacco",sci:"Pseudognaphalium bioletti",x:"u"},
{page:"two-fork clover",sci:"Trifolium amoenum",x:"u"},
{page:"twolobe clarkia",sci:"Clarkia biloba ssp. biloba",x:"u"},
{page:"twotooth buckwheat",sci:"Eriogonum viridescens",x:"u"},
{page:"unarmed buckwheat",sci:"Eriogonum inerme",x:"u"},
{page:"upright pepperweed",sci:"Lepidium strictum",x:"u"},
{page:"valley mayweed",sci:"Matricaria occidentalis",x:"u"},
{page:"valley tassels",sci:"Castilleja attenuata",x:"u"},
{page:"varied lupine",sci:"Lupinus variicolor",x:"u"},
{page:"veiny pepperweed",sci:"Lepidium oblongum",x:"u"},
{page:"viper's-bugloss",sci:"Echium vulgare",x:"o"},
{page:"virginia pepperweed",sci:"Lepidium virginicum",x:"u"},
{page:"wall bedstraw",sci:"Galium parisiense",x:"u"},
{page:"waltham creek clarkia",sci:"Clarkia modesta",x:"u"},
{page:"wand buckwheat",sci:"Eriogonum roseum",x:"u"},
{page:"wavyleaf ceanothus",sci:"Ceanothus foliosus",x:"u"},
{page:"wavyleaf paintbrush",sci:"Castilleja applegatei",x:"o"},
{page:"wayside pepper grass",sci:"Lepidium pinnatifidum",x:"u"},
{page:"west coast canada goldenrod",sci:"Solidago elongata",x:"u"},
{page:"western dock",sci:"Rumex occidentalis",x:"u"},
{page:"western dog violet",sci:"Viola adunca ssp. adunca",x:"u"},
{page:"western dogwood",sci:"Cornus sericea ssp. occidentalis",x:"u"},
{page:"western lily of the valley",sci:"Maianthemum dilatatum",x:"u"},
{page:"western morning glory",sci:"Calystegia occidentalis ssp. occidentalis",x:"u"},
{page:"western scouringrush",sci:"Equisetum hyemale ssp. affine",x:"u"},
{page:"western virgin's bower",sci:"Clematis ligusticifolia",x:"u"},
{page:"white peppermint",sci:"Eucalyptus pulchella",x:"u"},
{page:"white sweetclover",sci:"Melilotus albus",x:"u"},
{page:"white-tipped clover",sci:"Trifolium variegatum",x:"u"},
{page:"whitebark raspberry",sci:"Rubus leucodermis",x:"u"},
{page:"whitedaisy tidytips",sci:"Layia glandulosa",x:"u"},
{page:"whitney's farewell-to-spring",sci:"Clarkia amoena ssp. whitneyi",x:"u"},
{page:"wickerstem buckwheat",sci:"Eriogonum vimineum",x:"u"},
{page:"wild hyacinth",sci:"Dichelostemma multiflorum",x:"u"},
{page:"Rumex crassus",com:"willow dock",x:"u"},
{page:"Rumex salicifolius",com:"willow dock",x:"u"},
{page:"willowleaf lettuce",sci:"Lactuca saligna",x:"u"},
{page:"winter vetch",sci:"Vicia villosa ssp. varia",x:"u"},
{page:"wood forget-me-not",sci:"Myosotis sylvatica",x:"u"},
{page:"woodland tidytips",sci:"Layia gaillardioides",x:"u"},
{page:"woolly clover",sci:"Trifolium tomentosum",x:"u"},
{page:"woolly fiddleneck",sci:"Amsinckia spectabilis",x:"u"},
{page:"wright's buckwheat",sci:"Eriogonum wrightii",x:"u"},
{page:"wright's cudweed",sci:"Pseudognaphalium canescens",x:"u"},
{page:"Wyethia mollis",x:"u"},
{page:"yellow iris",sci:"Iris pseudacorus",x:"u"},
{page:"yellow sweetclover",sci:"Melilotus officinalis",x:"u"},
{page:"yellow vetch",sci:"Vicia lutea",x:"u"},
{page:"yellowray goldfields",sci:"Lasthenia glabrata",x:"u"},
];
