var pages=[
{page:"geranium family",key:true},
{page:"lupines",sci:"Lupinus",elab:"Lupinus spp.",key:true},
{page:"poppies",sci:"Eschscholzia",elab:"Eschscholzia spp.",key:true},
{page:"clovers",sci:"Trifolium",elab:"Trifolium spp.",key:true},
{page:"california poppy",sci:"Eschscholzia californica"},
{page:"stork's-bills",sci:"Erodium",elab:"Erodium spp.",key:true},
{page:"thistles",key:true},
{page:"paintbrushes",sci:"Castilleja",elab:"Castilleja spp.",key:true},
{page:"monkeyflowers",key:true},
{page:"vetches",sci:"Vicia",elab:"Vicia spp.",key:true},
{page:"wild hyacinths",sci:"Dichelostemma",elab:"Dichelostemma spp.",key:true},
{page:"orange bush monkeyflower",sci:"Diplacus aurantiacus"},
{page:"clarkia",sci:"Clarkia",elab:"Clarkia spp.",key:true},
{page:"brambles",sci:"Rubus",elab:"Rubus spp.",key:true},
{page:"western blue-eyed grass",sci:"Sisyrinchium bellum"},
{page:"nightshades",sci:"Solanum",elab:"Solanum spp.",key:true},
{page:"mallows and checkermallows",key:true},
{page:"geraniums and cranesbills",sci:"Geranium",elab:"Geranium spp.",key:true},
{page:"mariposa lilies",sci:"Calochortus",elab:"Calochortus spp.",key:true},
{page:"owl's clover",key:true},
{page:"common stork's-bill",sci:"Erodium cicutarium"},
{page:"checkerblooms and checkermallows",sci:"Sidalcea",elab:"Sidalcea spp.",key:true},
{page:"ceanothus",sci:"Ceanothus",elab:"Ceanothus spp.",key:true},
{page:"hedgenettles",sci:"Stachys",elab:"Stachys spp.",key:true},
{page:"mediterranean stork's-bill",sci:"Erodium botrys"},
{page:"shooting stars",key:true},
{page:"blue dicks",sci:"Dichelostemma capitatum"},
{page:"dwarf checkermallow",sci:"Sidalcea malviflora"},
{page:"forget-me-nots",sci:"Myosotis",elab:"Myosotis spp.",key:true},
{page:"hairy vetch",sci:"Vicia villosa"},
{page:"irises",sci:"Iris",elab:"Iris spp.",key:true},
{page:"triplet lilies",sci:"Triteleia",elab:"Triteleia spp.",key:true},
{page:"woodsorrels",sci:"Oxalis",elab:"Oxalis spp.",key:true},
{page:"broadleaf forget-me-not",sci:"Myosotis latifolia"},
{page:"miniature lupine",sci:"Lupinus bicolor"},
{page:"pacific hound's tongue",sci:"Adelinia grande"},
{page:"california blackberry",sci:"Rubus ursinus"},
{page:"ithuriel's spear",sci:"Triteleia laxa"},
{page:"tomcat clover",sci:"Trifolium willdenovii"},
{page:"indian paintbrushes",key:true},
{page:"sweet peas and vetchlings",sci:"Lathyrus",elab:"Lathyrus spp.",key:true},
{page:"bluewitch nightshade",sci:"Solanum umbelliferum"},
{page:"silver lupine",sci:"Lupinus albifrons"},
{page:"toyon",sci:"Heteromeles arbutifolia"},
{page:"common vetch",sci:"Vicia sativa"},
{page:"roses",sci:"Rosa",elab:"Rosa spp.",key:true},
{page:"california buckeye",sci:"Aesculus californica"},
{page:"milk thistle",sci:"Silybum marianum"},
{page:"daisies",key:true},
{page:"silverpuffs and blow wives in seed",key:true},
{page:"larkspurs",sci:"Delphinium",elab:"Delphinium spp.",key:true},
{page:"california hedge nettle",sci:"Stachys bullata"},
{page:"henderson's shooting star",sci:"Primula hendersonii"},
{page:"pacific poison oak",sci:"Toxicodendron diversilobum"},
{page:"purple owl's-clover",sci:"Castilleja exserta"},
{page:"blue-eyed marys",sci:"Collinsia",elab:"Collinsia spp.",key:true},
{page:"willowherbs",sci:"Epilobium",elab:"Epilobium spp.",key:true},
{page:"cut-leaved crane's-bill",sci:"Geranium dissectum"},
{page:"rose clover",sci:"Trifolium hirtum"},
{page:"Leptosiphon",com:"baby stars, linanthus, and leptosiphons",sci:"Leptosiphon",elab:"Leptosiphon spp.",key:true},
{page:"nemophila",com:"baby blue eyes",sci:"Nemophila",elab:"Nemophila spp.",key:true},
{page:"winecup clarkia",sci:"Clarkia purpurea",key:true},
{page:"california yerba santa",sci:"Eriodictyon californicum"},
{page:"indian warrior",sci:"Pedicularis densiflora"},
{page:"red maids",sci:"Calandrinia menziesii"},
{page:"bedstraws",sci:"Galium",elab:"Galium spp.",key:true},
{page:"sanicles",sci:"Sanicula",elab:"Sanicula spp.",key:true},
{page:"standard thistles",sci:"Cirsium",elab:"Cirsium spp.",key:true},
{page:"star thistles",sci:"Centaurea",elab:"Centaurea spp.",key:true},
{page:"blue elder",sci:"Sambucus cerulea"},
{page:"pacific pea",sci:"Lathyrus vestitus"},
{page:"purple chinese houses",sci:"Collinsia heterophylla"},
{page:"baby blue eyes",sci:"Nemophila menziesii"},
{page:"california fuchsia",sci:"Epilobium canum"},
{page:"gilias",sci:"Gilia",elab:"Gilia spp.",key:true},
{page:"honeysuckles",sci:"Lonicera",elab:"Lonicera spp.",key:true},
{page:"plumeless thistles",sci:"Carduus",elab:"Carduus spp.",key:true},
{page:"trilliums",sci:"Trillium",elab:"Trillium spp.",key:true},
{page:"bermuda buttercup",sci:"Oxalis pes-caprae"},
{page:"california bay",sci:"Umbellularia californica"},
{page:"catchweed bedstraw",sci:"Galium aparine"},
{page:"denseflower indian paintbrush",sci:"Castilleja densiflora"},
{page:"italian thistle",sci:"Carduus pycnocephalus"},
{page:"pink honeysuckle",sci:"Lonicera hispidula"},
{page:"western columbine",sci:"Aquilegia formosa"},
{page:"brodiaeas",sci:"Brodiaea",elab:"Brodiaea spp.",key:true},
{page:"salsifies",sci:"Tragopogon",elab:"Tragopogon spp.",key:true},
{page:"baldhip rose",sci:"Rosa gymnocarpa"},
{page:"bull thistle",sci:"Cirsium vulgare"},
{page:"coyote brush",sci:"Baccharis pilularis"},
{page:"coyote mint",sci:"Monardella villosa"},
{page:"dove's-foot crane's-bill",sci:"Geranium molle"},
{page:"fernald's iris",sci:"Iris fernaldii"},
{page:"redwood sorrel",sci:"Oxalis oregana"},
{page:"salsify",sci:"Tragopogon porrifolius"},
{page:"western star flower",sci:"Lysimachia latifolia"},
{page:"white globe lily",sci:"Calochortus albus"},
{page:"onions",sci:"Allium",elab:"Allium spp.",key:true},
{page:"sand-spurries",sci:"Spergularia",elab:"Spergularia spp.",key:true},
{page:"buckbrush",sci:"Ceanothus cuneatus"},
{page:"bush poppy",sci:"Dendromecon rigida"},
{page:"california sagebrush",sci:"Artemisia californica"},
{page:"pineapple-weed",sci:"Matricaria discoidea"},
{page:"purple sanicle",sci:"Sanicula bipinnatifida"},
{page:"woolly indian paintbrush",sci:"Castilleja foliolosa"},
{page:"yellow starthistle",sci:"Centaurea solstitialis"},
{page:"periwinkles",sci:"Vinca",elab:"Vinca spp.",key:true},
{page:"rabbit-tobaccos",sci:"Pseudognaphalium",elab:"Pseudognaphalium spp.",key:true},
{page:"sea figs and ice plants",sci:"Carpobrotus",elab:"Carpobrotus spp.",key:true},
{page:"blow wives",sci:"Achyrachaena mollis"},
{page:"coast indian paintbrush",sci:"Castilleja affinis"},
{page:"common daisy",sci:"Bellis perennis"},
{page:"greater periwinkle",sci:"Vinca major"},
{page:"padre's shooting star",sci:"Primula clevelandii"},
{page:"ruby chalice clarkia",sci:"Clarkia rubicunda"},
{page:"variable linanthus",sci:"Leptosiphon parviflorus"},
{page:"wartleaf ceanothus",sci:"Ceanothus papillosus"},
{page:"wild radish",sci:"Raphanus sativus"},
{page:"yellow mariposa lily",sci:"Calochortus luteus"},
{page:"harvest brodiaea",sci:"Brodiaea elegans"},
{page:"arroyo lupine",sci:"Lupinus succulentus"},
{page:"blueblossom",sci:"Ceanothus thyrsiflorus"},
{page:"butterfly mariposa lily",sci:"Calochortus venustus"},
{page:"california cudweed",sci:"Pseudognaphalium californicum"},
{page:"california gilia",sci:"Gilia achilleifolia"},
{page:"giant wakerobin",sci:"Trillium chloropetalum"},
{page:"thimbleberry",sci:"Rubus parviflorus"},
{page:"western vervain",sci:"Verbena lasiostachys"},
{page:"catchflies",sci:"Silene",elab:"Silene spp.",key:true},
{page:"field madder",sci:"Sherardia arvensis"},
{page:"Microseris",com:"silverpuffs",sci:"Microseris",elab:"Microseris spp.",key:true},
{page:"red larkspur",sci:"Delphinium nudicaule"},
{page:"sages",sci:"Salvia",elab:"Salvia spp.",key:true},
{page:"speedwells",sci:"Veronica",elab:"Veronica spp.",key:true},
{page:"Uropappus lindleyi",com:"silverpuffs",sci:"Uropappus lindleyi"},
{page:"bird's-eye speedwell",sci:"Veronica persica"},
{page:"broad-leaved sweet pea",sci:"Lathyrus latifolius"},
{page:"california pitcher sage",sci:"Lepechinia calycina"},
{page:"california wild rose",sci:"Rosa californica"},
{page:"checker lily",sci:"Fritillaria affinis"},
{page:"fiesta flower",sci:"Pholistoma auritum"},
{page:"himalayan blackberry",sci:"Rubus armeniacus"},
{page:"hop trefoil",sci:"Trifolium campestre"},
{page:"jeweled onion",sci:"Allium serra"},
{page:"modesty",sci:"Whipplea modesta"},
{page:"musk stork's-bill",sci:"Erodium moschatum"},
{page:"ookow",sci:"Dichelostemma congestum"},
{page:"red sand spurrey",sci:"Spergularia rubra"},
{page:"seep monkeyflower",sci:"Erythranthe guttata"},
{page:"centaurys",sci:"Zeltnera",elab:"Zeltnera spp.",key:true},
{page:"dwarf brodiaea",sci:"Brodiaea terrestris"},
{page:"mallows",sci:"Malva",elab:"Malva spp.",key:true},
{page:"red ribbons",sci:"Clarkia concinna",key:true},
{page:"snowberries",sci:"Symphoricarpos",elab:"Symphoricarpos spp.",key:true},
{page:"american vetch",sci:"Vicia americana"},
{page:"andrews' clintonia",sci:"Clintonia andrewsiana"},
{page:"bird's-eye gilia",sci:"Gilia tricolor"},
{page:"california spikenard",sci:"Aralia californica"},
{page:"calla lily",sci:"Zantedeschia aethiopica"},
{page:"chilean sea fig",sci:"Carpobrotus chilensis"},
{page:"common selfheal",sci:"Prunella vulgaris"},
{page:"cowbag clover",sci:"Trifolium depauperatum"},
{page:"douglas iris",sci:"Iris douglasiana"},
{page:"douglas' silverpuffs",sci:"Microseris douglasii"},
{page:"elegant clarkia",sci:"Clarkia unguiculata"},
{page:"four-spot",sci:"Clarkia purpurea quadrivulnera",elab:"Clarkia purpurea ssp. quadrivulnera"},
{page:"greenspot nightshade",sci:"Solanum douglasii"},
{page:"herb robert",sci:"Geranium robertianum"},
{page:"lesser hop trefoil",sci:"Trifolium dubium"},
{page:"narrow-leaved clover",sci:"Trifolium angustifolium"},
{page:"pacific trillium",sci:"Trillium ovatum"},
{page:"pipestem clematis",sci:"Clematis lasiantha"},
{page:"prickly sowthistle",sci:"Sonchus asper"},
{page:"purple star-thistle",sci:"Centaurea calcitrapa"},
{page:"rough hedgenettle",sci:"Stachys rigida"},
{page:"royal larkspur",sci:"Delphinium variegatum"},
{page:"sheep's sorrel",sci:"Rumex acetosella"},
{page:"small-flowered catchfly",sci:"Silene gallica"},
{page:"coralroots",sci:"Corallorhiza",elab:"Corallorhiza spp.",key:true},
{page:"currants and gooseberries",sci:"Ribes",elab:"Ribes spp.",key:true},
{page:"milkweeds",sci:"Asclepias",elab:"Asclepias spp.",key:true},
{page:"black nightshade",sci:"Solanum nigrum"},
{page:"black sage",sci:"Salvia mellifera"},
{page:"broad-leaved cattail",sci:"Typha latifolia"},
{page:"broad-leaved helleborine",sci:"Epipactis helleborine"},
{page:"california bee plant",sci:"Scrophularia californica"},
{page:"chia",sci:"Salvia columbariae"},
{page:"clay mariposa lily",sci:"Calochortus argillosus"},
{page:"clustered clover",sci:"Trifolium glomeratum"},
{page:"common snowberry",sci:"Symphoricarpos albus"},
{page:"davy's centaury",sci:"Zeltnera davyi"},
{page:"fringed checkerbloom",sci:"Sidalcea diploscypha"},
{page:"hairy ceanothus",sci:"Ceanothus oliganthus"},
{page:"oregon bitterroot",sci:"Lewisia rediviva"},
{page:"pacific aster",sci:"Symphyotrichum chilense"},
{page:"pacific sanicle",sci:"Sanicula crassicaulis"},
{page:"panicled willowherb",sci:"Epilobium brachycarpum"},
{page:"purple viper's-bugloss",sci:"Echium plantagineum"},
{page:"red vetchling",sci:"Lathyrus cicera"},
{page:"sand fringepod",sci:"Thysanocarpus curvipes"},
{page:"seaside daisy",sci:"Erigeron glaucus"},
{page:"slender iceplant",sci:"Mesembryanthemum nodiflorum"},
{page:"sticky sand-spurrey",sci:"Spergularia macrotheca"},
{page:"three-cornered garlic",sci:"Allium triquetrum"},
{page:"vinegar weed",sci:"Trichostema lanceolatum"},
{page:"white nemophila",sci:"Nemophila heterophylla"},
{page:"yellow bush lupine",sci:"Lupinus arboreus"},
{page:"zigzag larkspur",sci:"Delphinium patens"},
{page:"afro-australian daisies",sci:"Dimorphotheca",elab:"Dimorphotheca spp.",key:true},
{page:"belladonna lily",sci:"Amaryllis belladonna"},
{page:"Cirsium occidentale",com:"cobwebby thistle",sci:"Cirsium occidentale",key:true},
{page:"fountain thistle",sci:"Cirsium fontinale",key:true},
{page:"Microseris acuminata"},
{page:"alkali heath",sci:"Frankenia salina"},
{page:"alkali heliotrope",sci:"Heliotropium curassavicum"},
{page:"american black nightshade",sci:"Solanum americanum"},
{page:"american wild carrot",sci:"Daucus pusillus"},
{page:"brass buttons",sci:"Cotula coronopifolia"},
{page:"broadleaved pepperweed",sci:"Lepidium latifolium"},
{page:"bull clover",sci:"Trifolium fucatum"},
{page:"bull mallow",sci:"Malva nicaeensis"},
{page:"bunchleaf penstemon",sci:"Penstemon heterophyllus"},
{page:"california aster",sci:"Corethrogyne filaginifolia"},
{page:"california buckwheat",sci:"Eriogonum fasciculatum"},
{page:"california harebell",sci:"Campanula prenanthoides"},
{page:"california larkspur",sci:"Delphinium californicum"},
{page:"california milkweed",sci:"Asclepias californica"},
{page:"california milkwort",sci:"Rhinotropis californica"},
{page:"canyon gooseberry",sci:"Ribes menziesii"},
{page:"chaparral clarkia",sci:"Clarkia affinis"},
{page:"chaparral currant",sci:"Ribes malvaceum"},
{page:"chicory",sci:"Cichorium intybus"},
{page:"coast silk tassel",sci:"Garrya elliptica"},
{page:"coffeeberry",sci:"Frangula californica"},
{page:"congdon's monkeyflower",sci:"Diplacus congdonii"},
{page:"cottonbatting plant",sci:"Pseudognaphalium stramineum"},
{page:"cream sacs",sci:"Castilleja rubicundula lithospermoides",elab:"Castilleja rubicundula ssp. lithospermoides"},
{page:"creeping snowberry",sci:"Symphoricarpos mollis"},
{page:"crimson clover",sci:"Trifolium incarnatum"},
{page:"false babystars",sci:"Leptosiphon androsaceus"},
{page:"franciscan paintbrush",sci:"Castilleja subinclusa franciscana",elab:"Castilleja subinclusa ssp. franciscana"},
{page:"gambel's milkvetch",sci:"Astragalus gambelianus"},
{page:"graceful bedstraw",sci:"Galium porrigens"},
{page:"ground rose",sci:"Rosa spithamea"},
{page:"hairy bittercress",sci:"Cardamine hirsuta"},
{page:"hoary rock-rose",sci:"Cistus creticus"},
{page:"hooker's fairybells",sci:"Prosartes hookeri"},
{page:"kashmir balsam",sci:"Impatiens balfourii"},
{page:"large-flowered leptosiphon",sci:"Leptosiphon grandiflorus"},
{page:"mexicali onion",sci:"Allium peninsulare"},
{page:"monterey indian paintbrush",sci:"Castilleja latifolia"},
{page:"mount hamilton fountain thistle",sci:"Cirsium fontinale campylon",elab:"Cirsium fontinale ssp. campylon"},
{page:"muehlenberg's centaury",sci:"Zeltnera muehlenbergii"},
{page:"north californian indian pink",sci:"Silene laciniata californica",elab:"Silene laciniata ssp. californica"},
{page:"oxeye daisy",sci:"Leucanthemum vulgare"},
{page:"pacific mistletoe",sci:"Phoradendron leucarpum tomentosum",elab:"Phoradendron leucarpum ssp. tomentosum"},
{page:"pale pink-sorrel",sci:"Oxalis incarnata"},
{page:"passionflowers",sci:"Passiflora",elab:"Passiflora spp."},
{page:"pennyroyal",sci:"Mentha pulegium"},
{page:"poison sanicle",sci:"Sanicula bipinnata"},
{page:"purple foxglove",sci:"Digitalis purpurea"},
{page:"pussy-ears",sci:"Calochortus tolmiei"},
{page:"red hot poker",sci:"Kniphofia uvaria"},
{page:"red osier dogwood",sci:"Cornus sericea"},
{page:"red valerian",sci:"Centranthus ruber"},
{page:"reddish tufted vetch",sci:"Vicia benghalensis"},
{page:"rod wirelettuce",sci:"Stephanomeria virgata"},
{page:"rosy sandcrocus",sci:"Romulea rosea"},
{page:"san francisco collinsia",sci:"Collinsia multicolor"},
{page:"santa clara red ribbons",sci:"Clarkia concinna automixa",elab:"Clarkia concinna ssp. automixa"},
{page:"scarlet monkeyflower",sci:"Erythranthe cardinalis"},
{page:"sea fig",sci:"Carpobrotus edulis"},
{page:"serpentine leptosiphon",sci:"Leptosiphon ambiguus"},
{page:"shasta daisy",sci:"Leucanthemum maximum"},
{page:"skunkweed",sci:"Navarretia squarrosa"},
{page:"sky lupine",sci:"Lupinus nanus"},
{page:"slender phlox",sci:"Microsteris gracilis"},
{page:"spotted coralroot",sci:"Corallorhiza maculata"},
{page:"stinging lupine",sci:"Lupinus hirsutissimus"},
{page:"striped coralroot",sci:"Corallorhiza striata"},
{page:"sweet scabious",sci:"Sixalix atropurpurea"},
{page:"tree clover",sci:"Trifolium ciliolatum"},
{page:"tufted poppy",sci:"Eschscholzia caespitosa"},
{page:"venus thistle",sci:"Cirsium occidentale venustum",elab:"Cirsium occidentale ssp. venustum"},
{page:"wavyleaf paintbrush",sci:"Castilleja applegatei"},
{page:"western burning bush",sci:"Euonymus occidentalis"},
{page:"white blue-eyed mary",sci:"Collinsia bartsiifolia"},
{page:"white brodiaea",sci:"Triteleia hyacinthina"},
{page:"wind poppy",sci:"Papaver heterophyllum"},
{page:"woollypod milkweed",sci:"Asclepias eriocarpa"},
{page:"Clarkia concinna concinna",elab:"Clarkia concinna ssp. concinna"},
{page:"golden brodiaea"},
{page:"narrowleaf milkweed"},
{page:"trailing african daisy"},
{page:"yellow salsify"},
];
