var pages=[
{page:"geranium family",sci:"family Geraniaceae",key:true},
{page:"brodiaea-like flowers",sci:"subfamily Brodiaeoideae",key:true},
{page:"lupines",sci:"Lupinus spp.",key:true},
{page:"poppies",sci:"Eschscholzia spp.",key:true},
{page:"clovers",sci:"Trifolium spp.",key:true},
{page:"thistles",key:true},
{page:"california poppy",sci:"Eschscholzia californica"},
{page:"stork's-bills",sci:"Erodium spp.",key:true},
{page:"dandelion-like flowers",key:true},
{page:"paintbrushes",sci:"Castilleja spp.",key:true},
{page:"monkeyflowers",key:true},
{page:"clarkia",sci:"Clarkia spp.",key:true},
{page:"loosestrifes",sci:"Lysimachia spp.",key:true},
{page:"vetches",sci:"Vicia spp.",key:true},
{page:"orange bush monkeyflower",sci:"Diplacus aurantiacus"},
{page:"wild hyacinths",sci:"Dichelostemma spp.",key:true},
{page:"brambles",sci:"Rubus spp.",key:true},
{page:"bindweed family",sci:"family Convolvulaceae",key:true},
{page:"western blue-eyed grass",sci:"Sisyrinchium bellum"},
{page:"scarlet pimpernel",sci:"Lysimachia arvensis"},
{page:"mariposa lilies",sci:"Calochortus spp.",key:true},
{page:"nightshades",sci:"Solanum spp.",key:true},
{page:"false bindweeds",sci:"Calystegia spp.",key:true},
{page:"geraniums and cranesbills",sci:"Geranium spp.",key:true},
{page:"hedgenettles",sci:"Stachys spp.",key:true},
{page:"mallows and checkermallows",key:true},
{page:"owl's clover",key:true},
{page:"bittercresses",sci:"Cardamine spp.",key:true},
{page:"common stork's-bill",sci:"Erodium cicutarium"},
{page:"triplet lilies",sci:"Triteleia spp.",key:true},
{page:"ceanothus",sci:"Ceanothus spp.",key:true},
{page:"milkmaids",sci:"Cardamine californica"},
{page:"broadleaf forget-me-not",sci:"Myosotis latifolia"},
{page:"checkerblooms and checkermallows",sci:"Sidalcea spp.",key:true},
{page:"forget-me-nots",sci:"Myosotis spp.",key:true},
{page:"mediterranean stork's-bill",sci:"Erodium botrys"},
{page:"trefoils",key:true},
{page:"ithuriel's spear",sci:"Triteleia laxa"},
{page:"violets",sci:"Viola spp.",key:true},
{page:"blue dicks",sci:"Dichelostemma capitatum"},
{page:"california blackberry",sci:"Rubus ursinus"},
{page:"daisies",key:true},
{page:"dwarf checkermallow",sci:"Sidalcea malviflora"},
{page:"hairy vetch",sci:"Vicia villosa"},
{page:"miniature lupine",sci:"Lupinus bicolor"},
{page:"shooting stars",key:true},
{page:"california buckeye",sci:"Aesculus californica"},
{page:"indian paintbrushes",key:true},
{page:"irises",sci:"Iris spp.",key:true},
{page:"pacific hound's tongue",sci:"Adelinia grande"},
{page:"sweet peas and vetchlings",sci:"Lathyrus spp.",key:true},
{page:"woodsorrels",sci:"Oxalis spp.",key:true},
{page:"bluewitch nightshade",sci:"Solanum umbelliferum"},
{page:"milk thistle",sci:"Silybum marianum"},
{page:"mustard family",sci:"family Brassicaceae",key:true},
{page:"pacific false bindweed",sci:"Calystegia purpurata"},
{page:"tomcat clover",sci:"Trifolium willdenovii"},
{page:"winecup clarkia",sci:"Clarkia purpurea",key:true},
{page:"buttercups",sci:"Ranunculus spp.",key:true},
{page:"california hedge nettle",sci:"Stachys bullata"},
{page:"larkspurs",sci:"Delphinium spp.",key:true},
{page:"roses",sci:"Rosa spp.",key:true},
{page:"silver lupine",sci:"Lupinus albifrons"},
{page:"toyon",sci:"Heteromeles arbutifolia"},
{page:"blue-eyed marys",sci:"Collinsia spp.",key:true},
{page:"plantains",sci:"Plantago spp.",key:true},
{page:"purple owl's-clover",sci:"Castilleja exserta"},
{page:"spring beauties",sci:"Claytonia spp.",key:true},
{page:"Leptosiphon",com:"baby stars, linanthus, and leptosiphons",sci:"Leptosiphon spp.",key:true},
{page:"california buttercup",sci:"Ranunculus californicus"},
{page:"common yarrow",sci:"Achillea millefolium"},
{page:"honeysuckles",sci:"Lonicera spp.",key:true},
{page:"manroots",sci:"Marah spp.",key:true},
{page:"miner's lettuce",sci:"Claytonia perfoliata"},
{page:"pacific poison oak",sci:"Toxicodendron diversilobum"},
{page:"pink honeysuckle",sci:"Lonicera hispidula"},
{page:"silverpuffs and blow wives in seed",key:true},
{page:"tarweeds and allies",sci:"tribe Madieae",key:true},
{page:"willowherbs",sci:"Epilobium spp.",key:true},
{page:"california yerba santa",sci:"Eriodictyon californicum"},
{page:"common vetch",sci:"Vicia sativa"},
{page:"coyote mint",sci:"Monardella villosa"},
{page:"henderson's shooting star",sci:"Primula hendersonii"},
{page:"Monadrella",sci:"Monadrella spp.",key:true},
{page:"Monardella",sci:"Monardella spp.",key:true},
{page:"rose clover",sci:"Trifolium hirtum"},
{page:"star thistles",sci:"Centaurea spp.",key:true},
{page:"biscuitroots",sci:"Lomatium spp.",key:true},
{page:"cut-leaved crane's-bill",sci:"Geranium dissectum"},
{page:"docks",sci:"Rumex spp.",key:true},
{page:"mule's ears",sci:"Wyethia spp.",key:true},
{page:"ribwort plantain",sci:"Plantago lanceolata"},
{page:"standard thistles",sci:"Cirsium spp.",key:true},
{page:"woolly sunflowers",sci:"Eriophyllum spp.",key:true},
{page:"Nemophila",com:"baby blue eyes",sci:"Nemophila spp.",key:true},
{page:"brodiaeas",sci:"Brodiaea spp.",key:true},
{page:"california manroot",sci:"Marah fabacea"},
{page:"deervetch",sci:"Acmispon spp.",key:true},
{page:"elders",sci:"Sambucus spp.",key:true},
{page:"indian warrior",sci:"Pedicularis densiflora"},
{page:"red maids",sci:"Calandrinia menziesii"},
{page:"bedstraws",sci:"Galium spp.",key:true},
{page:"blue elder",sci:"Sambucus cerulea"},
{page:"italian thistle",sci:"Carduus pycnocephalus"},
{page:"pacific pea",sci:"Lathyrus vestitus"},
{page:"pale flax",sci:"Linum bienne"},
{page:"plumeless thistles",sci:"Carduus spp.",key:true},
{page:"popcorn flowers",sci:"Plagiobothrys spp.",key:true},
{page:"purple chinese houses",sci:"Collinsia heterophylla"},
{page:"sanicles",sci:"Sanicula spp.",key:true},
{page:"trilliums",sci:"Trillium spp.",key:true},
{page:"woodland stars",sci:"Lithophragma spp.",key:true},
{page:"baby blue eyes",sci:"Nemophila menziesii"},
{page:"beaked hawksbeard",sci:"Crepis vesicaria ssp. taraxacifolia"},
{page:"bermuda buttercup",sci:"Oxalis pes-caprae"},
{page:"bird's-foot-trefoils",sci:"Lotus spp.",key:true},
{page:"bull thistle",sci:"Cirsium vulgare"},
{page:"butterfly mariposa lily",sci:"Calochortus venustus"},
{page:"california bay",sci:"Umbellularia californica"},
{page:"california fuchsia",sci:"Epilobium canum"},
{page:"catchweed bedstraw",sci:"Galium aparine"},
{page:"common dandelion",sci:"Taraxacum officinale"},
{page:"denseflower indian paintbrush",sci:"Castilleja densiflora"},
{page:"fiddlenecks",sci:"Amsinckia spp.",key:true},
{page:"four-spot",sci:"Clarkia purpurea ssp. quadrivulnera"},
{page:"fremont's deathcamas",sci:"Toxicoscordion fremontii"},
{page:"gilias",sci:"Gilia spp.",key:true},
{page:"hawksbeard",sci:"Crepis spp.",key:true},
{page:"rusty popcornflower",sci:"Plagiobothrys nothofulvus"},
{page:"salsifies",sci:"Tragopogon spp.",key:true},
{page:"western columbine",sci:"Aquilegia formosa"},
{page:"western heart's ease",sci:"Viola ocellata"},
{page:"yellow starthistle",sci:"Centaurea solstitialis"},
{page:"baldhip rose",sci:"Rosa gymnocarpa"},
{page:"Bellardia",sci:"Bellardia spp.",key:true},
{page:"bird's-foot trefoil",sci:"Lotus corniculatus"},
{page:"california golden violet",sci:"Viola pedunculata"},
{page:"california sagebrush",sci:"Artemisia californica"},
{page:"coyote brush",sci:"Baccharis pilularis"},
{page:"dove's-foot crane's-bill",sci:"Geranium molle"},
{page:"fernald's iris",sci:"Iris fernaldii"},
{page:"harvest brodiaea",sci:"Brodiaea elegans"},
{page:"manzanitas",sci:"Arctostaphylos spp.",key:true},
{page:"ocean spray",sci:"Holodiscus discolor"},
{page:"redwood sorrel",sci:"Oxalis oregana"},
{page:"ruby chalice clarkia",sci:"Clarkia rubicunda"},
{page:"salsify",sci:"Tragopogon porrifolius"},
{page:"sand-spurries",sci:"Spergularia spp.",key:true},
{page:"tidy tips",sci:"Layia platyglossa"},
{page:"tidytips",sci:"Layia spp.",key:true},
{page:"western star flower",sci:"Lysimachia latifolia"},
{page:"white globe lily",sci:"Calochortus albus"},
{page:"woodland madia",sci:"Anisocarpus madioides"},
{page:"wormwoods and sagebrushes",sci:"Artemisia spp.",key:true},
{page:"yellow mariposa lily",sci:"Calochortus luteus"},
{page:"blueblossom",sci:"Ceanothus thyrsiflorus"},
{page:"buckbrush",sci:"Ceanothus cuneatus"},
{page:"bush poppy",sci:"Dendromecon rigida"},
{page:"common daisy",sci:"Bellis perennis"},
{page:"false solomon's seals",sci:"Maianthemum spp.",key:true},
{page:"golden yarrow",sci:"Eriophyllum confertiflorum"},
{page:"greater periwinkle",sci:"Vinca major"},
{page:"hop trefoils",key:true},
{page:"mediterranean lineseed",sci:"Bellardia trixago"},
{page:"onions",sci:"Allium spp.",key:true},
{page:"periwinkles",sci:"Vinca spp.",key:true},
{page:"pineapple-weed",sci:"Matricaria discoidea"},
{page:"poison hemlock",sci:"Conium maculatum"},
{page:"purple sanicle",sci:"Sanicula bipinnatifida"},
{page:"rabbit-tobaccos",sci:"Pseudognaphalium spp.",key:true},
{page:"thimbleberry",sci:"Rubus parviflorus"},
{page:"variable linanthus",sci:"Leptosiphon parviflorus"},
{page:"woolly indian paintbrush",sci:"Castilleja foliolosa"},
{page:"arroyo lupine",sci:"Lupinus succulentus"},
{page:"bindweeds",sci:"Convolvulus spp.",key:true},
{page:"blow wives",sci:"Achyrachaena mollis"},
{page:"broad-leaved sweet pea",sci:"Lathyrus latifolius"},
{page:"california cudweed",sci:"Pseudognaphalium californicum"},
{page:"cat's ears",sci:"Hypochaeris spp.",key:true},
{page:"centaurys",sci:"Zeltnera spp.",key:true},
{page:"coast indian paintbrush",sci:"Castilleja affinis"},
{page:"deerweed",sci:"Acmispon glaber"},
{page:"false solomon's seal",sci:"Maianthemum racemosum"},
{page:"field bindweed",sci:"Convolvulus arvensis"},
{page:"hillside woodland star",sci:"Lithophragma heterophyllum"},
{page:"indian teasel",sci:"Dipsacus sativus"},
{page:"padre's shooting star",sci:"Primula clevelandii"},
{page:"sea figs and ice plants",sci:"Carpobrotus spp.",key:true},
{page:"shortpod mustard",sci:"Hirschfeldia incana"},
{page:"teasels",sci:"Dipsacus spp.",key:true},
{page:"wartleaf ceanothus",sci:"Ceanothus papillosus"},
{page:"western vervain",sci:"Verbena lasiostachys"},
{page:"wild radish",sci:"Raphanus sativus"},
{page:"woollyfruit desertparsley",sci:"Lomatium dasycarpum"},
{page:"bristly oxtongue",sci:"Helminthotheca echioides"},
{page:"cabbages and mustards",sci:"Brassica spp.",key:true},
{page:"california bee plant",sci:"Scrophularia californica"},
{page:"california gilia",sci:"Gilia achilleifolia"},
{page:"california goldfields",sci:"Lasthenia californica"},
{page:"california wild rose",sci:"Rosa californica"},
{page:"chile trefoil",sci:"Acmispon wrangelianus"},
{page:"common cat's-ear",sci:"Hypochaeris radicata"},
{page:"common chickweed",sci:"Stellaria media"},
{page:"common cowparsnip",sci:"Heracleum maximum"},
{page:"creamcups",sci:"Platystemon californicus"},
{page:"elegant clarkia",sci:"Clarkia unguiculata"},
{page:"foothill desert-parsley",sci:"Lomatium utriculatum"},
{page:"fritillaries",sci:"Fritillaria spp.",key:true},
{page:"giant wakerobin",sci:"Trillium chloropetalum"},
{page:"gumplants",sci:"Grindelia spp.",key:true},
{page:"himalayan blackberry",sci:"Rubus armeniacus"},
{page:"medicks",sci:"Medicago spp.",key:true},
{page:"pacific trillium",sci:"Trillium ovatum"},
{page:"rancher's fiddleneck",sci:"Amsinckia menziesii var. intermedia"},
{page:"red sand spurrey",sci:"Spergularia rubra"},
{page:"smooth mule-ears",sci:"Wyethia glabra"},
{page:"sun cup",sci:"Taraxia ovata"},
{page:"tarweeds",sci:"Madia spp.",key:true},
{page:"bird's-eye speedwell",sci:"Veronica persica"},
{page:"bur clover",sci:"Medicago polymorpha"},
{page:"california pitcher sage",sci:"Lepechinia calycina"},
{page:"california spikenard",sci:"Aralia californica"},
{page:"catchflies",sci:"Silene spp.",key:true},
{page:"chamise",sci:"Adenostoma fasciculatum"},
{page:"checker lily",sci:"Fritillaria affinis"},
{page:"curly dock",sci:"Rumex crispus"},
{page:"false babystars",sci:"Leptosiphon androsaceus"},
{page:"field madder",sci:"Sherardia arvensis"},
{page:"field mustard",sci:"Brassica rapa"},
{page:"fiesta flower",sci:"Pholistoma auritum"},
{page:"greenspot nightshade",sci:"Solanum douglasii"},
{page:"hayfield tarweed",sci:"Hemizonia congesta"},
{page:"hillside false bindweed",sci:"Calystegia subacaulis ssp. subacaulis"},
{page:"hop trefoil",sci:"Trifolium campestre"},
{page:"jeweled onion",sci:"Allium serra"},
{page:"modesty",sci:"Whipplea modesta"},
{page:"musk stork's-bill",sci:"Erodium moschatum"},
{page:"narrow-leaved clover",sci:"Trifolium angustifolium"},
{page:"narrowleaf mule-ears",sci:"Wyethia angustifolia"},
{page:"ookow",sci:"Dichelostemma congestum"},
{page:"purple star-thistle",sci:"Centaurea calcitrapa"},
{page:"red larkspur",sci:"Delphinium nudicaule"},
{page:"rough hedgenettle",sci:"Stachys rigida"},
{page:"sages",sci:"Salvia spp.",key:true},
{page:"san francisco woodland-star",sci:"Lithophragma affine"},
{page:"scorpionweeds",sci:"Phacelia spp.",key:true},
{page:"seablushes",sci:"Plectritis spp.",key:true},
{page:"seep monkeyflower",sci:"Erythranthe guttata"},
{page:"Uropappus lindleyi",com:"silverpuffs",sci:"Uropappus lindleyi"},
{page:"Microseris",com:"silverpuffs",sci:"Microseris spp.",key:true},
{page:"small melilot",sci:"Melilotus indicus"},
{page:"sow thistles",sci:"Sonchus spp.",key:true},
{page:"speedwells",sci:"Veronica spp.",key:true},
{page:"stinking chamomile",sci:"Anthemis cotula"},
{page:"american vetch",sci:"Vicia americana"},
{page:"american yellowrocket",sci:"Barbarea orthoceras"},
{page:"andrews' clintonia",sci:"Clintonia andrewsiana"},
{page:"bird's-eye gilia",sci:"Gilia tricolor"},
{page:"black nightshade",sci:"Solanum nigrum"},
{page:"california goldenrod",sci:"Solidago velutina ssp. californica"},
{page:"california milkwort",sci:"Rhinotropis californica"},
{page:"california plantain",sci:"Plantago erecta"},
{page:"calla lily",sci:"Zantedeschia aethiopica"},
{page:"chicory",sci:"Cichorium intybus"},
{page:"chilean sea fig",sci:"Carpobrotus chilensis"},
{page:"common hedge parsley",sci:"Torilis arvensis"},
{page:"common selfheal",sci:"Prunella vulgaris"},
{page:"cotoneaster",sci:"Cotoneaster spp.",key:true},
{page:"cowbag clover",sci:"Trifolium depauperatum"},
{page:"douglas iris",sci:"Iris douglasiana"},
{page:"douglas' silverpuffs",sci:"Microseris douglasii"},
{page:"dwarf brodiaea",sci:"Brodiaea terrestris"},
{page:"fiddle dock",sci:"Rumex pulcher"},
{page:"goldenbushes",sci:"Ericameria spp.",key:true},
{page:"hairy gumweed",sci:"Grindelia hirsutula"},
{page:"herb robert",sci:"Geranium robertianum"},
{page:"johnnytuck",sci:"Triphysaria eriantha"},
{page:"lesser hop trefoil",sci:"Trifolium dubium"},
{page:"longhorn seablush",sci:"Plectritis macrocera"},
{page:"mallows",sci:"Malva spp.",key:true},
{page:"milkweeds",sci:"Asclepias spp.",key:true},
{page:"pipestem clematis",sci:"Clematis lasiantha"},
{page:"plums & cherries",sci:"Prunus spp."},
{page:"prickly sowthistle",sci:"Sonchus asper"},
{page:"red ribbons",sci:"Clarkia concinna",key:true},
{page:"royal larkspur",sci:"Delphinium variegatum"},
{page:"seaside woolly sunflower",sci:"Eriophyllum staechadifolium"},
{page:"sheep's sorrel",sci:"Rumex acetosella"},
{page:"skunkweed",sci:"Navarretia squarrosa"},
{page:"small-flowered catchfly",sci:"Silene gallica"},
{page:"snowberries",sci:"Symphoricarpos spp.",key:true},
{page:"white hawkweed",sci:"Hieracium albiflorum"},
{page:"yellow bush lupine",sci:"Lupinus arboreus"},
{page:"bent-flowered fiddleneck",sci:"Amsinckia lunaris"},
{page:"big berry manzanita",sci:"Arctostaphylos glauca"},
{page:"black sage",sci:"Salvia mellifera"},
{page:"broad-leaved cattail",sci:"Typha latifolia"},
{page:"broad-leaved helleborine",sci:"Epipactis helleborine"},
{page:"cattails",sci:"Typha spp.",key:true},
{page:"chia",sci:"Salvia columbariae"},
{page:"clay mariposa lily",sci:"Calochortus argillosus"},
{page:"clustered clover",sci:"Trifolium glomeratum"},
{page:"coast silk tassel",sci:"Garrya elliptica"},
{page:"coast tarweed",sci:"Madia sativa"},
{page:"coastal manroot",sci:"Marah oregana"},
{page:"Cirsium occidentale",com:"cobwebby thistle",sci:"Cirsium occidentale",key:true},
{page:"common madia",sci:"Madia elegans"},
{page:"common snowberry",sci:"Symphoricarpos albus"},
{page:"coralroots",sci:"Corallorhiza spp.",key:true},
{page:"crevice alumroot",sci:"Heuchera micrantha"},
{page:"currants and gooseberries",sci:"Ribes spp.",key:true},
{page:"davy's centaury",sci:"Zeltnera davyi"},
{page:"franciscan paintbrush",sci:"Castilleja subinclusa ssp. franciscana"},
{page:"fringed checkerbloom",sci:"Sidalcea diploscypha"},
{page:"fringed willowherb",sci:"Epilobium ciliatum"},
{page:"golden brodiaea",sci:"Triteleia ixioides ssp. ixioides"},
{page:"golden-fleece",sci:"Ericameria arborescens"},
{page:"gray mule-ears",sci:"Wyethia helenioides"},
{page:"hairy ceanothus",sci:"Ceanothus oliganthus"},
{page:"helleborines",sci:"Epipactis spp.",key:true},
{page:"hoary rock-rose",sci:"Cistus creticus"},
{page:"late cotoneaster",sci:"Cotoneaster coriaceus"},
{page:"lettuces",sci:"Lactuca spp.",key:true},
{page:"mountain phacelia",sci:"Phacelia imbricata"},
{page:"muehlenberg's centaury",sci:"Zeltnera muehlenbergii"},
{page:"oregon bitterroot",sci:"Lewisia rediviva"},
{page:"pacific aster",sci:"Symphyotrichum chilense"},
{page:"pacific sanicle",sci:"Sanicula crassicaulis"},
{page:"panicled willowherb",sci:"Epilobium brachycarpum"},
{page:"peak rushrose",sci:"Helianthemum scoparium"},
{page:"peruvian peppertree",sci:"Schinus molle"},
{page:"purple viper's-bugloss",sci:"Echium plantagineum"},
{page:"q-tips",com:"Q tips",sci:"Micropus californicus"},
{page:"red vetchling",sci:"Lathyrus cicera"},
{page:"sand fringepod",sci:"Thysanocarpus curvipes"},
{page:"santa clara red ribbons",sci:"Clarkia concinna ssp. automixa"},
{page:"sea muilla",sci:"Muilla maritima"},
{page:"seaside daisy",sci:"Erigeron glaucus"},
{page:"short-flower deervetch",sci:"Acmispon parviflorus"},
{page:"silk tassel",sci:"Garrya spp.",key:true},
{page:"silver wattle",sci:"Acacia dealbata"},
{page:"slender iceplant",sci:"Mesembryanthemum nodiflorum"},
{page:"sticky cinquefoil",sci:"Drymocallis glandulosa"},
{page:"sticky sand-spurrey",sci:"Spergularia macrotheca"},
{page:"stream violet",sci:"Viola glabella"},
{page:"sweet fennel",sci:"Foeniculum vulgare"},
{page:"three-cornered garlic",sci:"Allium triquetrum"},
{page:"threeleaf foamflower",sci:"Tiarella trifoliata"},
{page:"venus thistle",sci:"Cirsium occidentale var. venustum"},
{page:"vinegar weed",sci:"Trichostema lanceolatum"},
{page:"wallflowers",sci:"Erysimum spp.",key:true},
{page:"white nemophila",sci:"Nemophila heterophylla"},
{page:"wild buckwheats",sci:"Eriogonum spp.",key:true},
{page:"zigzag larkspur",sci:"Delphinium patens"},
{page:"afro-australian daisies",key:true},
{page:"alkali heath",sci:"Frankenia salina"},
{page:"alkali heliotrope",sci:"Heliotropium curassavicum"},
{page:"american black nightshade",sci:"Solanum americanum"},
{page:"american wild carrot",sci:"Daucus pusillus"},
{page:"belladonna lily",sci:"Amaryllis belladonna"},
{page:"bitter lettuce",sci:"Lactuca virosa"},
{page:"black mustard",sci:"Brassica nigra"},
{page:"brass buttons",sci:"Cotula coronopifolia"},
{page:"broadleaved pepperweed",sci:"Lepidium latifolium"},
{page:"bull clover",sci:"Trifolium fucatum"},
{page:"bull mallow",sci:"Malva nicaeensis"},
{page:"bunchleaf penstemon",sci:"Penstemon heterophyllus"},
{page:"california aster",sci:"Corethrogyne filaginifolia"},
{page:"california buckwheat",sci:"Eriogonum fasciculatum"},
{page:"california goldenbanner",sci:"Thermopsis californica"},
{page:"california goldenbush",sci:"Ericameria ericoides"},
{page:"california harebell",sci:"Campanula prenanthoides"},
{page:"california larkspur",sci:"Delphinium californicum"},
{page:"california milkweed",sci:"Asclepias californica"},
{page:"canyon gooseberry",sci:"Ribes menziesii"},
{page:"carrots",sci:"Daucus spp.",key:true},
{page:"chaparral clarkia",sci:"Clarkia affinis"},
{page:"chaparral currant",sci:"Ribes malvaceum"},
{page:"chestnuts",sci:"Castanea spp."},
{page:"Clarkia concinna concinna",sci:"Clarkia concinna ssp. concinna"},
{page:"clustered dock",sci:"Rumex conglomeratus"},
{page:"coast range agoseris",sci:"Agoseris hirsuta"},
{page:"coastal brookfoam",sci:"Boykinia occidentalis"},
{page:"coffeeberry",sci:"Frangula californica"},
{page:"common silverweed",sci:"Potentilla anserina"},
{page:"common sow-thistle",sci:"Sonchus oleraceus"},
{page:"common st. john's-wort",sci:"Hypericum perforatum"},
{page:"common woolly sunflower",sci:"Eriophyllum lanatum"},
{page:"congdon's monkeyflower",sci:"Diplacus congdonii"},
{page:"cottonbatting plant",sci:"Pseudognaphalium stramineum"},
{page:"cream sacs",sci:"Castilleja rubicundula ssp. lithospermoides"},
{page:"creeping snowberry",sci:"Symphoricarpos mollis"},
{page:"crimson clover",sci:"Trifolium incarnatum"},
{page:"distant phacelia",sci:"Phacelia distans"},
{page:"douglas' meadowfoam",sci:"Limnanthes douglasii"},
{page:"dwarf popcornflower",sci:"Plagiobothrys humistratus"},
{page:"field marigold",sci:"Calendula arvensis"},
{page:"fountain thistle",sci:"Cirsium fontinale",key:true},
{page:"fragrant fritillary",sci:"Fritillaria liliacea"},
{page:"gambel's milkvetch",sci:"Astragalus gambelianus"},
{page:"golden chinquapin",sci:"Chrysolepis chrysophylla"},
{page:"graceful bedstraw",sci:"Galium porrigens"},
{page:"grassy tarweed",sci:"Madia gracilis"},
{page:"great valley gumweed",sci:"Grindelia camporum"},
{page:"ground rose",sci:"Rosa spithamea"},
{page:"hairy bittercress",sci:"Cardamine hirsuta"},
{page:"henderson's angelica",sci:"Angelica hendersonii"},
{page:"Holocarpha",sci:"Holocarpha spp.",key:true},
{page:"hooker's fairybells",sci:"Prosartes hookeri"},
{page:"kashmir balsam",sci:"Impatiens balfourii"},
{page:"large-flowered leptosiphon",sci:"Leptosiphon grandiflorus"},
{page:"leafless wintergreen",sci:"Pyrola aphylla"},
{page:"lemon balm",sci:"Melissa officinalis"},
{page:"longspur seablush",sci:"Plectritis ciliosa"},
{page:"mexicali onion",sci:"Allium peninsulare"},
{page:"Microseris acuminata",sci:"Microseris acuminata"},
{page:"monterey indian paintbrush",sci:"Castilleja latifolia"},
{page:"mount hamilton fountain thistle",sci:"Cirsium fontinale var. campylon"},
{page:"naked buckwheat",sci:"Eriogonum nudum"},
{page:"narrowleaf milkweed",sci:"Asclepias fascicularis"},
{page:"north californian indian pink",sci:"Silene laciniata ssp. californica"},
{page:"oregon gumplant",sci:"Grindelia stricta"},
{page:"oxeye daisy",sci:"Leucanthemum vulgare"},
{page:"pacific mistletoe",sci:"Phoradendron leucarpum ssp. tomentosum"},
{page:"pale pink-sorrel",sci:"Oxalis incarnata"},
{page:"pallid manzanita",sci:"Arctostaphylos pallida"},
{page:"passionflowers",sci:"Passiflora spp."},
{page:"pennyroyal",sci:"Mentha pulegium"},
{page:"pit-gland tarweed",sci:"Holocarpha virgata"},
{page:"poison sanicle",sci:"Sanicula bipinnata"},
{page:"purple foxglove",sci:"Digitalis purpurea"},
{page:"pussy-ears",sci:"Calochortus tolmiei"},
{page:"red hot poker",sci:"Kniphofia uvaria"},
{page:"red osier dogwood",sci:"Cornus sericea"},
{page:"red valerian",sci:"Centranthus ruber"},
{page:"reddish tufted vetch",sci:"Vicia benghalensis"},
{page:"redwood violet",sci:"Viola sempervirens"},
{page:"rod wirelettuce",sci:"Stephanomeria virgata"},
{page:"rosilla",sci:"Helenium puberulum"},
{page:"rosy sandcrocus",sci:"Romulea rosea"},
{page:"rough-fruited buttercup",sci:"Ranunculus muricatus"},
{page:"round-leaved crane's-bill",sci:"Geranium rotundifolium"},
{page:"san francisco collinsia",sci:"Collinsia multicolor"},
{page:"san francisco wallflower",sci:"Erysimum franciscan"},
{page:"scarlet monkeyflower",sci:"Erythranthe cardinalis"},
{page:"sea fig",sci:"Carpobrotus edulis"},
{page:"serpentine leptosiphon",sci:"Leptosiphon ambiguus"},
{page:"shasta daisy",sci:"Leucanthemum maximum"},
{page:"shepherd's-needle",sci:"Scandix pecten-veneris"},
{page:"sky lupine",sci:"Lupinus nanus"},
{page:"slender phlox",sci:"Microsteris gracilis"},
{page:"smooth cat's ear",sci:"Hypochaeris glabra"},
{page:"smooth tare",sci:"Vicia tetrasperma"},
{page:"spotted coralroot",sci:"Corallorhiza maculata"},
{page:"spotted medick",sci:"Medicago arabica"},
{page:"star-flowered lily-of-the-valley",sci:"Maianthemum stellatum"},
{page:"sticky snakeroot",sci:"Ageratina adenophora"},
{page:"stinging lupine",sci:"Lupinus hirsutissimus"},
{page:"striped coralroot",sci:"Corallorhiza striata"},
{page:"striped treasureflower",sci:"Gazania linearis"},
{page:"sweet alyssum",sci:"Lobularia maritima"},
{page:"sweet scabious",sci:"Sixalix atropurpurea"},
{page:"trailing african daisy",sci:"Dimorphotheca fruticosa"},
{page:"tree clover",sci:"Trifolium ciliolatum"},
{page:"tufted poppy",sci:"Eschscholzia caespitosa"},
{page:"water primrose",sci:"Ludwigia hexapetala"},
{page:"wavyleaf paintbrush",sci:"Castilleja applegatei"},
{page:"western burning bush",sci:"Euonymus occidentalis"},
{page:"western wallflower",sci:"Erysimum capitatum"},
{page:"white blue-eyed mary",sci:"Collinsia bartsiifolia"},
{page:"white brodiaea",sci:"Triteleia hyacinthina"},
{page:"white clover",sci:"Trifolium repens"},
{page:"wight's paint brush",sci:"Castilleja wightii"},
{page:"wild mustard",sci:"Sinapis arvensis"},
{page:"wind poppy",sci:"Papaver heterophyllum"},
{page:"wirelettuce",sci:"Stephanumeria spp.",key:true},
{page:"woollypod milkweed",sci:"Asclepias eriocarpa"},
{page:"yellow glandweed",sci:"Bellardia viscosa"},
{page:"yellow salsify",sci:"Tragopogon dubius"},
{page:"american red elder",sci:"Sambucus racemosa ssp. racemosa"},
{page:"wavy leafed soap plant"},
];
