var pages=[
["california poppy",1,2],
["turkey vulture",1,2,3,4,5,6],
["sticky monkeyflower",1,2,3],
["columbian black-tailed deer",1,2,3,5,7,9],
["blue dicks","","-2"],
["red-tailed hawk",1,2,3,4,5,6],
["western blue-eyed grass",1,2,3,4],
["scarlet pimpernel",1,2,3,4,5],
["mediterranean stork's-bill",1,2,3,4,5],
["redstem stork's-bill",1,2,3,4,5],
["milkmaids",1,2,3],
["california buckeye",1,2,3,4,5,"5a",6,7],
["pacific poison oak",1,2,3],
["toyon",1,2,3,4,5,6],
["ithuriel's spear",1,2,3],
["pink honeysuckle","","-2","-3"],
["hairy vetch","","-2"],
["california buttercup",1,2,3,4,5,6],
["western fence lizard",1,2],
["miniature lupine","",3,5],
["pacific hound's tongue",1,2,3,4],
["bluewitch nightshade",1,2,4,7],
["common yarrow",1,2,3,4,5],
["blue elder",1,2,3,4,5,6],
["california blackberry",1,2,3,4,6,7],
["dwarf checkermallow","","-2","-3","-4"],
["california hedge nettle",1,2,3],
["miner's lettuce",1,2,3,4,5,6],
["silver lupine",2,3,4],
["pacific pea",0,1,3,5],
["henderson's shooting star","","-2","-3","-4"],
["california scrub-jay",1,2,3,4],
["wild turkey",1,2,5,6,8],
["california bay","","-2","-3","-4"],
["milk thistle",1,2,3,4],
["red maids","","-2"],
["california beeplant",1,2,3,4,5],
["broadleaf forget-me-not",1,2,3,4],
["california manroot",1,2,3,4],
["purple owl's-clover",1,2,3],
["catchweed bedstraw",1,2,3,4],
["poison hemlock",1,2,3,5],
["baldhip rose","","-2","-3","-4",5],
["coyote brush",1,2,3,4],
["spring vetch",1,2,3],
["california ground squirrel",1,2,3],
["california yerba santa",1,2,4,5,8],
["western honey bee",1,2,3],
["bull thistle","","-2"],
["rose clover","","-2","-3"],
["acorn woodpecker",1,2,3,7,8],
["dove's-foot crane's-bill",1,2,3],
["ribwort plantain",1,2,3],
["mallard",1,2],
["tomcat clover",1,2,3],
["bermuda buttercup",1,2],
["western bluebird",1,4,6],
["common raven",1,3,6],
["california golden violet",1,2],
["california sagebrush",1,2],
["coyote mint",1,2,3,4],
["curly dock",1,"1b",2,3,4,5,6,7],
["cut-leaved crane's-bill",1,2,3],
["ruby chalice clarkia","","-2"],
["wavy-leafed soap plant",0,1,2,"2e",3],
["yellow star-thistle",1,2,3,4],
["variable checkerspot",1,2,3,6,7],
["rusty popcornflower",1,2,3,4,5,6],
["shining pepperweed",1,2,3],
["american coot",1,2],
["pale flax",1,2,3,4],
["rough hedgenettle",1,2,3],
["white globe lily","","-2",3,"3d",4],
["french broom",1,2,3,4,5,6,7],
["california banana slug",1],
["chamise",1,2,"2f",3,4],
["ocean spray",1,2,"2b",3,4],
["arroyo lupine",1,2,3,4],
["fuller's teasel",2,5],
["pacific madrone",1,2,3,4,"4b",5,6],
["padre's shooting star","","-2","-3"],
["pineapple-weed",1,2],
["deerweed",1,2,3],
["four-spot",1,2,3],
["purple salsify",1,2,3,4,5],
["golden yarrow",1,2,3,4,5,7],
["coffeeberry",1,4,5,7,9],
["field bindweed",1,2,3,4,5],
["california fuchsia",1,2,3],
["california wild rose",1,2,3,4,5,6],
["common chickweed",1,2,3],
["fremont's deathcamas",1,2,3,4],
["solomon's plume",1,2,3,4,5],
["fiddle dock","-m",0,1,2,7],
["greater periwinkle","","-2"],
["warrior's plume",1,2],
["beaked hawksbeard",1,2,3,4,5],
["coast paintbrush",1,2],
["dark-eyed junco",1,2,3],
["chick lupine",1,2,3,4,5,6,7,8],
["giant wakerobin","","-2"],
["hillside woodland star","",5],
["purple sanicle","","-2","-3",4,5],
["western columbine",1,2,3,4,"4f",5],
["bird's-foot trefoil",1,2,3,4,5],
["denseflower indian paintbrush",1,2,3],
["common cowparsnip",1,2,"2a","2b",3,4,5],
["big berry manzanita","","-2","-3"],
["bristly oxtongue",1,2,3,4,5],
["musk stork's-bill",1,2,3,4],
["purple chinese houses",1,2,3,4],
["small melilot",1,2,3],
["bur clover",1,2,3],
["chile trefoil",00,01,1],
["harvest brodiaea",1,2,3],
["italian thistle","","-2"],
["rancher's fiddleneck",1,2],
["california quail",1,2,7],
["bigleaf maple",1,2,3],
["california cudweed",1,2,3,4,5],
["european stinging nettle",3,5,6],
["false babystars","","-2","-3"],
["red-winged blackbird",1,4,5,6],
["redwood sorrel",1,2,3],
["western starflower",1,2,5],
["yellow mariposa lily","","-2",3],
["greater quaking grass",1,2,3,5],
["hayfield tarweed",1,2,4],
["ookow",1,2,3],
["woodland madia",1,2,3,4,5,6],
["canada goose",1,3],
["buckbrush",1,2,3,5],
["butterfly mariposa lily",1,2,3,4],
["california pitcher sage",1,2,3,4],
["golden-crowned sparrow",1,3],
["himalayan blackberry",1,2,3,4,5,8],
["western vervain",1,2,3,5],
["blow wives","",2,3,5],
["smooth mule-ears",1,2,3],
["american kestrel",4,5,6],
["chaparral pea",1,2,3],
["sun cup",1,2,3],
["california gilia",1,2,3],
["elegant clarkia",1,2],
["fernald's iris","","-2"],
["q-tips",1,2,3,4],
["red sand spurrey",1,2,"2b",3,4,"4b"],
["seep monkeyflower",1,2,3,4],
["thimbleberry",1,2,3,4,5],
["western heart's ease",1,2,3,4],
["yellow-faced bumble bee",1,"1c",2],
["pacific aster","","-2",5],
["woolly indian paintbrush","",2,3,4,6],
["california goldfields",1,2,3,4,5,6],
["painted lady",1,"1b",3,"3b",4,7],
["steller's jay",1,2,3],
["creamcups",1,2,3,4],
["northern harrier",4,5,6],
["blueblossom",1,2,3,4,5],
["california huckleberry",0,1,2,3],
["mediterranean lineseed",1,2,3,4,5],
["pacific trillium",1,2,3,4],
["wild radish",1,2,3],
["woodland strawberry",1,2,3],
["common cat's-ear",1,2,3,4,5,6,7],
["gray buckeye",1,3],
["wild boar",1,4,7],
["california newt",1,3],
["coyote",0,1,2,6],
["anna's hummingbird",2,3,5],
["coast live oak",1,"4c","4i",5,"6c"],
["pipestem clematis","","-2","-3","-4"],
["spanish broom",1,2,3],
["baby blue eyes",1,2,7],
["california sister",1,2,6],
["hillside gooseberry",1,2,"2f",3,4],
["prickly sowthistle","1a","2a","2e",4,5],
["western jack-o'-lantern",2,4,6],
["california maidenhair fern",1],
["fennel",2,"2c",3,5],
["pearly everlasting",1,2,3,4],
["shepherd's-purse",1,2,3,4],
["wolf spiders",1],
["american white pelican",1,6,7],
["bird's-eye gilia","","-2"],
["braun's giant horsetail",1,2,6],
["common daisy",1,2,3],
["fringed willowherb",1,2,3,"3b","3e",4],
["graceful bedstraw","",2,"2f",3],
["pacific sanicle","","-2","-3"],
["shortpod mustard",1,2,3,4],
["snowy egret",1,6,7],
["white hawkweed",1,2,3,4,5,6],
["woollyfruit desertparsley",1,2,4,5],
["great egret",1,3,6],
["silver bush lupine",1],
["common madia",1,2,3,4],
["hairy brackenfern",1,2,3],
["horned lark",1,2],
["pacific gopher snake",1,6],
["american robin",1,2,3,4,5],
["bush poppy",1,"1-2",2],
["nasturtium",1,2,5],
["western sword fern",1,2,3],
["american black nightshade",1,2,3,4],
["black sage",1,2,3,4,5],
["brown pelican",1,2,6,7],
["california gall wasp",1,2],
["coast silk tassel","-1","-2",1,2,3,"3b",4],
["douglas iris",1,2,3],
["fiesta flower","","-2",3],
["flaccid cryptantha",1,3,6],
["foothill desert-parsley","",3],
["peruvian peppertree",1,2,3],
["shepherd's-needle",1,2,3],
["silverpuffs","Uropappus lindleyi,"],
["sky lupine","-3",1,2,3,5,6],
["wartleaf ceanothus",1,2,5,6],
["coast tarweed",1,2,3,4],
["tidy tips",1,2,3,5],
["california towhee",1,2,4],
["double crested cormorant",1,2,3,6],
["white-tailed kite","",5],
["american yellowrocket",1,2,3],
["bristly dogtail grass",1,2,3,4],
["california hazelnut",0,1,2,4],
["common snowberry","","-2"],
["common st. john's-wort",1,2,3,4],
["convergent lady beetle",1,2,3,4,8],
["longhorn seablush",1,2,3,4],
["naked buckwheat",1,2,3,4],
["red larkspur",1,2,3,5,7],
["seven-spotted lady beetle",1,2,3],
["variable linanthus",1,2,3,4],
["vinegar weed","","-2"],
["broad-leaved sweet pea","","-2"],
["butter-and-eggs",1,2,3],
["california ringlet",3,4],
["chaparral currant",1,2,3,5],
["great blue heron",1,2,3,6,7],
["narrowleaf mule-ears",1,2,3,4],
["seaside woolly sunflower",1,2,3,4],
["giant chain fern",1,2,3],
["brush rabbit",1,2,4],
["common selfheal",1,2,7],
["field madder","","-2","-3"],
["fox squirrel",1,2],
["house finch",1,3],
["pacific harbor seal",3],
["pacific velvet ant",1],
["black nightshade",1,2,3],
["broad-leaved helleborine",1,2,3,4,5],
["bur chervil",1,2],
["california goldenrod",1,2,3,8],
["california plantain",1,2,3,4],
["checker lily",1,2,3,4,5],
["cherry-plum",2,3,4,5],
["clay mariposa lily","","-2",3],
["coastal manroot",1,2,3,4],
["common hedge parsley",1,2,3,4,5],
["creeping snowberry","","-2"],
["crevice alumroot",1,2,3,5],
["heart-podded hoary cress",1,"1b",2,3,4],
["jeweled onion",""],
["narrow-leaved clover","","-2","-3"],
["rosilla",1,2,3,4],
["say's phoebe",1,5],
["valley popcornflower",1,2,3],
["american vetch",""],
["anise swallowtail",1,3],
["common dandelion",1,2],
["dwarf brodiaea",1,2],
["hairy gumweed",1,2,3,4],
["pampas grass",""],
["stinking chamomile",1,2,3,4],
["white baby blue eyes",3,7],
["black-tailed jackrabbit",1,2],
["northern pacific rattlesnake",3,4,8],
["western pond turtle",1],
["yellow-billed magpie",1,2,3,4],
["american crow",1,7],
["california condor",1,3],
["california spikenard",1,2,3,4,5,7],
["calla lily","","-2"],
["modesty",1,2,3,4],
["mophead hydrangea",1,2,3,5],
["slender phlox","",2,3],
["western gray squirrel",1],
["bird's-eye speedwell",1,2],
["black-tailed bumble bee",1,2],
["bull mallow",1,3,5],
["california lady beetle",1],
["california larkspur",1,2,"2d",3],
["chicory",1,2,3],
["domestic mallard","",2],
["goldenrod crab spider",1,2],
["hop trefoil",1,2],
["late cotoneaster",0,1,2],
["lesser hop trefoil",1,2],
["narrowleaf milkweed",1,2,3],
["sagebrush woolly stem gall midge",1],
["sand fringepod",""],
["santa cruz aquatic garter snake",1],
["sheep's sorrel","","-2",3],
["silverleaf cotoneaster",1,5],
["small-flowered catchfly",1,2,3],
["star-flowered lily-of-the-valley",1,2],
["tasmanian blue gum",0,1,2,3],
["three-cornered garlic",1,2,3],
["western gull",1,3,6,7],
["yellow bush lupine",2,3,"3f",4,5,7],
["gray mule-ears",1,2,3,4,5,6],
["pacific coast tick",1,6],
["wall barley",1,2,5],
["bay checkerspot",1],
["common woolly sunflower",1,2,5,6],
["mylitta crescent",1],
["waxcaps",3,4],
["botta's pocket gopher",2,4,6],
["alkali heath","",2],
["bald eagle",4],
["california king snake",1],
["coastal woodfern",""],
["golden eagle",4],
["lark sparrow",1,3],
["ring-necked duck",1,2],
["violet-green swallow",2,8],
["western meadowlark",1,3],
["bent-flowered fiddleneck",1,2],
["bigseed biscuitroot",1,5],
["brittleleaf manzanita",1,2,3,4,7],
["chia",1,2,3,5],
["chilean sea fig",1,2],
["common ivy",2,4,5,6,7],
["fringed checkerbloom",1,2,3],
["greenspot nightshade","","-2"],
["heermann's gull",1],
["hoary rock-rose","","-2","-3","-4"],
["little-robin",1,2],
["mountain phacelia",1,2,3],
["oneleaf foamflower",1,3,4,5],
["panicled willowherb",1,2,3],
["red-shouldered hawk",1,2,4,5],
["san francisco woodland-star",1,2],
["silver wattle",1,2,3,5],
["skunkweed",1,2,3],
["turkey tangle frogfruit",1,2,3],
["varied carpet beetle",1,6],
["vivid dancer",1,2,3],
["western boxelder bug",1],
["douglas' silverpuffs",""],
["field mustard",1,2,3,4,5],
["hillside false bindweed",1,2,3,4],
["mountain sweet cicely",1,2],
["pacific false bindweed",1,2,3,4],
["purple pampas grass",1,2],
["purple star-thistle",1,2,3],
["smooth cat's ear",1,2,3],
["grassy tarweed",1,2,3],
["venus thistle",1,2],
["dendroalsia moss",1,4,8],
["the prince",2,3,6,7],
["american bullfrog",1],
["goldback fern",""],
["western ladyfern",1,2],
["alaska yellowjacket",0,1],
["andrews' clintonia",1,2,3],
["black necked stilt",1],
["california milkwort","","-2"],
["coffee fern",1],
["eastern gray squirrel",1,4],
["grass spiders",3,5],
["long-bodied cellar spider",1,2],
["mediterranean spiny false wolf spider",1,2,3],
["mouse spider",1],
["osoberry",0,1,2,3],
["peak rushrose",1,2,3,4],
["purple foxglove","",5,6,7],
["red valerian","","-2","-3"],
["spider wasps",1,2],
["spotted towhee",1,2],
["sticky cinquefoil",1,2,3,4],
["sticky snakeroot",1,2,3,4],
["sweet alyssum",1,2,3,7],
["white-breasted nuthatch",1,2],
["wood, mound, and field ants","Formica,1",3],
["alkali heliotrope",1,2,3,4],
["almond",1],
["genus Anthaxia",1,2],
["banana passionfruit",1,2,3],
["bluets",1],
["broadleaf lupine",1,2,3,4,5,6],
["california alligator lizard",1],
["california aster","",2],
["california black oak",1,4,6],
["california chicory",1,2,3,4],
["california milkweed",1,2,3,4],
["california mugwort",1,2],
["chaparral clarkia","","-2"],
["chinquapin flower gall wasp",1],
["common centaury",1,2,6],
["cowbag clover","","-2","-3"],
["coyote brush bud gall midge",1,7],
["golden-fleece",1,2,3],
["goldenthread",7],
["hairy bittercress",1,2,6],
["hairy-pitted stork's-bill",1,2,5],
["leather oak",1,8],
["leopard lily",1,2,3,4,6,8,9],
["longspur seablush",1,2,3],
["montara manzanita",0,1,3,5,6,8],
["muehlenberg's centaury",1,2,3,4],
["oak mistletoe",1,2],
["painted meadow grasshopper",1,2,3,4],
["pale pink-sorrel","","-2"],
["poison sanicle",1,2],
["purple viper's-bugloss",1,2],
["queen anne's lace",1,2,3,4,5],
["redwood violet",1,2,3],
["rose-of-sharon",1,"1b",2,3,4,7],
["santa clara valley dudleya",2,7],
["slender iceplant",1,2],
["striped coralroot","","-2",3],
["tiger moths",7],
["true babystars","","-2"],
["white clover",1,2,4,6,7,8],
["zigzag larkspur","","-2","-3"],
["black mustard",1,2,3],
["brewer's ragwort",1,2,4,5,6,8],
["Chrysolepis chrysophylla var. chrysophylla",1,2,3],
["Chrysolepis chrysophylla var. minor",1,2,3],
["fiery skipper",1,3,4],
["holly-leaved cherry",1,2,"2c",3],
["margined calligrapher",1],
["most beautiful jewelflower",1,2,3,4,5],
["oregon gumplant",1,2,3],
["oxeye daisy",1,2,6],
["pale swallowtail",1,3],
["rabbitfoot grass",1,2,3,4,5],
["red vetchling",1,2,3],
["santa barbara daisy",1,2,3],
["seaside daisy",1,2,3],
["short-flower deervetch",1,2,3],
["silvery blue",1,3,4],
["spanish clover",1,2,3,6,8],
["tall flatsedge",1,2,8],
["northern checkerspot",1],
["woodland tidytips",1,2,5],
["pin molds",3,6],
["lace lichen",3,6],
["signal crayfish",1],
["sulphur tuft",3,5],
["western mosquitofish",1],
["witch's butter",4],
["aphids",1],
["coast redwood","",2,5,6],
["four-lined silverfish",1],
["mourning dove",1,6],
["northern mockingbird",1,5],
["pacific ringneck snake",1],
["rock pigeon",1,2],
["slender banana slug",1],
["turkey-tail",4,6],
["barn swallow",7,8],
["belladonna lily",1,2],
["braconid wasps",1],
["brandt's cormorant",3],
["brown-headed cowbird",1],
["california polypody",1,3],
["carpenter ants",1,3],
["cliff swallow",7],
["coast garter snake",1,3],
["coastal brookfoam","","-2","-3"],
["common merganser",1,2],
["fendler's meadow-rue",0,1,"1f",2,3],
["kashmir balsam","","-2"],
["large carpenter bees",1],
["olive",1,2,3,4,5,6],
["oregon bitterroot","","-2"],
["rosy sandcrocus","","-2","-3"],
["sweet scabious","",2,3,4],
["western yellowjacket",1,2],
["yellow-rumped warbler",1,2],
["andre's harvester ant",1],
["arroyo willow",1,2,3],
["bigelow's sneezeweed",""],
["black wattle",1,2,3],
["bufflehead",1],
["bull clover","","-2","-3"],
["california buckwheat",1,2,4,7],
["california bumble bee",1,3],
["california scrub oak",5,6,7],
["genus Calliphora","Calliphora,1",2,3],
["clustered clover","","-2"],
["clustered dock",1,2],
["coastal larkspur",1,2,3,4,5],
["genus Coelocnemis",1,3],
["fewflower blue-eyed mary",1,2,6],
["flax-flowered linanthus",1,2,3,6],
["goldentop grass",1,3,7],
["greater bee fly",2,3],
["ground rose","","-2","-3"],
["hairy ceanothus","","-2"],
["henderson's angelica",1,2,3,5,6],
["herb robert",1,4],
["hooker's fairybells","","-2"],
["japanese honeysuckle",1,2],
["magnificent seep monkeyflower",1,2,3],
["metallic sweat bees",1,2],
["mexicali onion",1,2],
["genus Mordella",1],
["orchard grass",0,1,2,3],
["ornate checkered beetle",1,2,5],
["pacific tent caterpillar",7,8],
["pennyroyal",1,2,3,5],
["pink everlasting",1,2,5,8],
["potato mirid",1,2],
["pride of madeira",1,"1a",2],
["genus Pristoceuthophilus",1,2],
["red ironbark",0,1,2,3],
["red osier dogwood",1,2,"2b","2c",3],
["redberry buckthorn",3,5,8],
["rose campion",1,2,3],
["rough stink bugs",1],
["rough-fruited buttercup",1,2],
["royal larkspur","","-2","-3"],
["san francisco collinsia","",2],
["san francisco wallflower",1,7],
["sea muilla",1,2,3],
["seaside buckwheat",1,2],
["serpentine leptosiphon",""],
["shade phacelia",1,2,5,7],
["spiny leaf gall wasp",1],
["stinging lupine",0,1,2,3,4,5,6],
["stream violet",1,2,3],
["sweet pittosporum",3,4,7],
["tanoak",1,2,3,4],
["western black-legged tick",1,3],
["western sycamore",1,4,5,8],
["white blue-eyed mary",""],
["white nemophila",1,2,3,4],
["white-crowned sparrow",1,3],
["willow apple gall sawfly",1,2],
["willow dock",1,2],
["wind poppy",1,2,5],
["big squirreltail",2,3,4],
["bitter lettuce",1,2,3,4,5],
["california balsamroot",1,2,3],
["california tortoiseshell",1],
["canyon gooseberry","","-2","-3"],
["common groundsel",1,2],
["common hareleaf",1,2,6],
["common sow-thistle",1,2,3,4],
["cream sacs",""],
["field marigold",1,2,5,7],
["franciscan paintbrush","","-2",5],
["fuchsiaflower gooseberry",1,7],
["horseweed",0,1,2,3,5,8],
["prickly lettuce",1,2,3,5,6,7,8,9],
["propertius duskywing",1],
["reddish tufted vetch",""],
["santa clara red ribbons",""],
["scots broom",3,4,5,6,7,8],
["seaside agoseris",1,2,5],
["sessileflower false goldenaster",1,2],
["shasta daisy",1,2,3],
["smooth tare",1,2],
["genus Tipula","Tipula,1",2,3],
["yellow salsify",1,2,3],
["american lady",1,7],
["blood currant",1,2,3,4],
["cabbage white",1],
["echo azure",3],
["fitch's tarweed",1],
["golden brodiaea",1,2],
["margined white",1],
["mount hamilton fountain thistle",1,2,3],
["Paeromopus angusticeps",1],
["yellow-spotted millipede",1,2,3],
["bull kelp",6,8],
["apricot jelly",5],
["beard lichens",3,6],
["common bird's nest fungus",3,5,7],
["common carp",2],
["common earthworm",1],
["common pill woodlouse",1],
["coral fungi",3,6],
["dog vomit slime mold",4],
["garden snail",5],
["giant sawgill",3,6],
["golden ear",3,6],
["golden-eye lichen",4],
["largemouth bass",1],
["nitrous bonnet",3,6],
["oakmoss",4],
["oyster mushroom",2,4,6],
["pinecone amanita",3,6],
["Prionitis lanceolata",7],
["stinking orange oyster",3,6],
["stubble rosegill",3,6],
["trooping crumble cap",3,6],
["western jumbo gym",3,6],
["yellow cellar slug",4],
["american black bear",8],
["american shrewmole",3],
["band-tailed pigeon",9],
["broad-footed mole",3],
["california whiptail",1],
["chestnut backed chickadee",3,5],
["coast douglas-fir",3,8],
["common raccoon",8],
["conifer chicken of the woods",2,4,7],
["downy woodpecker",1,3],
["dyer's polypore",5,7],
["european starling",""],
["gilled polypore",2,4,6],
["northern flicker",1],
["northern red belt",4],
["osprey",2],
["pied-billed grebe",1],
["red-eared slider",1],
["rosy conk",3,6],
["ruby-crowned kinglet",1],
["veiled polypore",4],
["western toad",1,3],
["willow bead gall mite",1],
["american century plant",1,2],
["american trailplant",3,4,5,7],
["artist's bracket",3,6],
["birchleaf mountain mahogany",5,8],
["bobcat",5],
["brewer's blackbird",1],
["bullock's oriole",1,2],
["california fetid adderstongue",1,2,3,4],
["california sea lion",5],
["coastal goldenbush",1,2,6],
["common aerial yellowjacket",1],
["common silverweed",1,2,3],
["desert cottontail",1,2],
["drugstore beetle",1],
["durango root",1,2,3,4],
["european paper wasp",1,2],
["feral pigeon",1],
["field penny-cress",1,2],
["firethorns",4,6,8],
["five-finger fern",1,2,3],
["flesh flies",1,2,3],
["forster's tern",1,6],
["gadwall",1],
["gambel's milkvetch",""],
["lemon balm",1,2],
["lesser goldfinch",1],
["longlegged sac spiders",1],
["manzanita leafgall aphid",3],
["merriam's chipmunk",0,1],
["monterey cypress",3,5],
["monterey pine",1,2,3],
["nested polypody",1,3],
["nomad bees",1],
["non-biting midges",1,2],
["north american jerusalem crickets",1],
["northern shoveler",1,2],
["orange-crowned warbler",1,5],
["pacific ninebark",1,2,7],
["Pagaronia triunata",1],
["genus Panurginus","Panurginus spp.,1"],
["primrose jasmine",1,5,7],
["pygmy nuthatch",1],
["red baneberry",3,5,6,7],
["ruddy duck",1],
["rufous-crowned sparrow",1],
["san francisco alligator lizard",1],
["savannah sparrow",1],
["sidewalk mites",1,2],
["southern sea otter",4],
["spurges",1,2],
["summer snowflake",1,7],
["tripartite sweat bee",1],
["water parsley",1,2],
["western burning bush",1,2,5],
["western drywood termite",1,2],
["western leatherwood",1,5,7],
["western subterranean termite",1,3],
["white horehound",5,7],
["white-haired monk longhorn",1,3],
["white-throated swift",4],
["wilson's warbler",1,3],
["wing-tapping cicadas",6,7],
["alderney crane's-bill",1,2],
["american wild carrot",1,2],
["Ampedus cordifer",1,2],
["aphid mummy wasps",4],
["artichoke thistle",7],
["asian lady beetle",1],
["Asphondylia garryae",5,6],
["bearded iris",1,2,3],
["black phoebe",5],
["blackwood",3,5,7],
["blue dock beetle",1],
["blue oak",1,2],
["blue skullcap",1,2],
["bowltube iris",1,2,3,4],
["brass buttons","","-2","-3"],
["broadleaved pepperweed",1,2],
["brown marmorated stink bug",1,2],
["bunch-flowered daffodil",1,3,4,7],
["bunchleaf penstemon",""],
["buttonhook leaf-beetle humping spider",1],
["california bee assassin",2],
["california bordered plant bug",1],
["california goldenbanner",1,2,3],
["california goldenbush",1,2],
["california goosefoot",1,2],
["california gull",6],
["california harebell",1,2,3,4],
["california saxifrage",1,2,5],
["canyon live oak",5,6],
["canyon liveforever",1,2,5],
["Chrysolina bankii",1],
["clark's sphinx",3],
["coast piperia",1,2],
["common goldeneye",1],
["common ramping-fumitory",1,2],
["common water strider",1],
["cooper's hawk",5],
["cottonbatting plant",1,2,6],
["crimson clover",1,2],
["cross orbweaver",3],
["cutworm moths and allies",1,2,7],
["dagger moths",7],
["desert stink beetles",1,2,4],
["diablo range garter snake",5],
["genus Dialysis","Dialysis,1"],
["distant phacelia",""],
["dobie pod",1,2],
["dwarf popcornflower",1,2,3],
["dwarf woodsorrel",1,2,7],
["genus Eulonchus","Eulonchus,1"],
["false grass-poly",1,2],
["fontana grasshopper",1,2,3],
["foothill carpenter bee",2,3,5],
["foothill larkspur",1,2,3,4],
["fragrant fritillary",1,2],
["genus Gammarotettix",1,2],
["gray's anemone",1],
["great mullein",2,4,6,8],
["greater yellowlegs",1],
["gypsum springbeauty",1,2,3,4],
["hartweg's umbrellawort",1,5],
["hermit thrush",1,2,3],
["hoary manzanita",1],
["hollyleaf redberry",3],
["house mouse",1],
["hyssop loosestrife",1,2,5,8],
["genus Irbisia","Irbisia,1",2],
["italian arum",5,6],
["jersey cudweed",1,2,5],
["johnson's jumping spider",1],
["kellogg's yampah",1,2,5],
["large-flowered leptosiphon","","-2"],
["subgenus Lasioglossum",1,2,3],
["leafless wintergreen",1,2,3],
["limoniid crane flies",1],
["live oak bud gall wasp",1],
["long billed curlew",1],
["Lytta crotchii",1],
["marbled godwit",1],
["mediterranean seed bug",1],
["mission prickly-pear",1,2,3],
["Molorchus longicollis",1,2],
["mountain fringepod",1,2,3,4],
["naples garlic",1,2,3,4],
["narrowleaf cottonrose",1],
["north californian indian pink",1,2],
["genus Orgyia",7,8],
["pacific glasswort",1],
["pallid manzanita",""],
["pallid-winged grasshopper",1],
["phacelia plant bug",1],
["pinpoint clover",2,5],
["pufftails",1,2],
["purua grass","Bolboschoenus,1",2,3,4],
["rancheria clover",1,2,5],
["redwood inside-out flower",1,2,5,6],
["salad burnet",2,5],
["san bernardino larkspur",1,2,3,4],
["scarlet monkeyflower","","-2","-3"],
["scudder's bush katydids",1],
["sea fig","","-2"],
["silver dollar gum",1,2,3,4,5],
["small-flowered nemophila",1,3,5],
["small-leaf monkeyflower",1,2,5],
["southern green stink bug",1,4],
["spotted coralroot",""],
["spotted cucumber beetle",1],
["spotted orbweaver",1],
["striped treasureflower",1],
["summer lupine",1,2,5,7],
["sydney golden wattle",1,2,3],
["genus Syneta",1,2],
["tabby moths",1],
["table mountain meadowfoam",1,2,3,4],
["tolmie's pussy-ears",1,2,3],
["tree clover","","-2"],
["tufted poppy",1,2,3],
["turkey pea",1,2],
["tutsan",1,2,3,4],
["valley oak",1],
["van houtte's columbine",1,2,3,6],
["viper's-bugloss",""],
["water primrose",""],
["western azalea",2,5,8],
["western buttercup",1,2,3],
["western wallflower",1,2,3],
["white fiesta flower",3],
["white ramping-fumitory",1,5],
["white-lined sphinx",1,4],
["whitebark raspberry",5,7],
["wild mustard",1,2,3],
["woolly clover",1,2],
["woollypod milkweed","","-2"],
["yellow glandweed",1,2],
["angled pea",1,2,3,5],
["beach sandspurry",1,2,3],
["black rat",9],
["Brachysomida californica",1],
["broad-leaved cattail",""],
["california glowworm",1],
["coast range agoseris",1,2,3],
["coastal burnweed",1,2,3],
["common european greenbottle fly",1],
["common wood-nymph",3],
["conical trashline orbweaver",3],
["dimorphic flower longhorn beetle",1,2],
["european red elder",3,5,6],
["flame skimmer",1],
["forked globetail",1],
["giant western crane fly",1,2,3],
["great valley gumweed",1,2,3],
["harding grass",1,2,4],
["hedge mustard",1,2,3,4],
["lotus hairstreak",3],
["Microseris acuminata",""],
["monterey indian paintbrush","","-2"],
["narrow-leaved cattail",1,5],
["philadelphia fleabane",1,2,3],
["pink plectritis",1,5],
["Podabrus cavicollis",1,2],
["potato gall midge",1,2],
["purple needlegrass",2,4],
["rayless ragwort",1,2,3,4],
["red brome",1,2],
["red ribbons","Clarkia concinna ssp. concinna,1",2],
["rod wirelettuce","","-2"],
["sara orangetip",3],
["spearleaf agoseris",1,3,5],
["spotted medick",3],
["tall fescue",1,2,5],
["threadleaf groundsel",1,2,5],
["trailing african daisy",1,2],
["umber skipper",1,3],
["umbrella papyrus",5],
["western calligrapher",1],
["western sweet coltsfoot",5,6],
["western tiger swallowtail",1],
["white brodiaea","","-2"],
["widow skimmer",1],
["wight's paint brush",1,2,3],
["wild oat",3,5],
["willowleaf lettuce",1,2,3,6],
["woolly distaff thistle",1,2,3,4],
["acmon blue",7],
["common spikeweed",1,5,7],
["pacific fritillary",1],
["pit-gland tarweed",1],
["sticky western rosinweed",1,5,7],
["Strophiona tigrina",1],
["west coast lady",1],
["woodland woollythreads",1,2,6],
["blackberry orange rust",3],
["common greenshield lichen",3],
["haircap mosses",3,6],
["tree lungwort",5],
["wolf lichen",3,6],
["Exobasidium arctostaphyli",3,4],
["Exobasidium vaccinii-uliginosi",1],
["bristle flies",1,3],
["camphor tree",1,2,3,4,5,6,9],
["chestnuts",1,2],
["dance flies",1],
["fringe cups",1,2,5,6,7],
["oleander",1,"1c",2,3,7],
["red hot poker","","-2"],
["watercress",1,"1a",4],
["western redbud",1,3,5,8],
["western skink",1,2,3],
["western wild ginger",7],
["yerba buena",2,7],
["big deervetch",2,5],
["black-margined flower fly",1,2],
["california phacelia",1,2,5],
["candy flower",1,2,5,7],
["chinese pistache",1,2],
["congdon's monkeyflower","","-2"],
["cretan mallow",1,2,3,5,6],
["Dicerca hornii ssp. hornii",1,2,4],
["false hawkbit",1,2,5],
["franchet's cotoneaster",1,2,7],
["hairy woodsorrel",1,2,5],
["hummingbird sage",1,2,4,6],
["island mallow",1,2,4,7],
["largeflower fairybells",1,2,3,5],
["live oak apple gall wasp",6],
["northern california black walnut",5,6,"6h"],
["notchleaf clover",1,2,5],
["persian walnut",4,6],
["rayless arnica",1,2,6],
["red alder",3,4,5,6,7],
["red passionflower",1,2],
["rosemary",1,2],
["ruptured twig gall wasp",5],
["salmonberry",4,5,7],
["santa catalina island buckwheat",2,5,8],
["spider gum",1,2,3],
["thimbleberry gallmaker",3,4],
["varied lupine",1,5],
["veiny monardella",1,2,3,7],
["western chokecherry",1,7],
["white alder",4,5],
["white poplar",6],
["white sage",2,7],
["wiry snapdragon",1,6],
["yellow v moth",1],
["big saltbush",1,5,7],
["california sweet grass",1,7],
["coast twinberry",1,3,4,5],
["coffeeberry midrib gall moth",4,6],
["foothill deervetch",2,7],
["giant vetch",1,2,3,5,6],
["hairy vetchling",1,2,5],
["narrow-leaf bird's-foot trefoil",1,5],
["rush broom",2,5],
["short-styled thistle",1,2,7],
["genus Stenocorus","Stenocorus,1",2],
["velvetgrass",3,4,5,6,7],
["western small milkweed bug",1],
["checkerspot caterpillars",7,8],
["gulf fritillary",1],
["flower glossary","figures/san francisco woodland star.svg","figures/california poppy.svg","figures/yellow mariposa lily.svg","figures/seep monkeyflower.svg","figures/california manroot.svg","figures/sea muilla.svg","figures/california poppy fruit.svg"],
["larkspur glossary","figures/foothill larkspur.svg","figures/foothill larkspur spur.svg","figures/foothill larkspur.svg","figures/foothill larkspur spur.svg"],
["legume glossary","figures/chaparral pea.svg"],
["orchid glossary","figures/coast piperia.svg"],
["insect glossary","figures/fly side.svg"],
["beetle glossary","figures/beetle.jpg"],
["true bug glossary","figures/true bug top.svg","figures/true bug side.svg"],
["bay area","figures/bay-area.jpg"],
];
